/**
 * Hand-authored Taiwanese forms for the HSK 3 vocabulary.
 *
 * Written from knowledge of the language first and checked against the extract afterwards, the
 * same way as HSK 2 and for the same reason: by this level the everyday word is often not the
 * character in front of you. 跑步 is 走 but 走 is 行; 生气 is 受氣; 饿 is 枵; 渴 is 喙焦; 筷子 is
 * 箸; 自行车 is 跤踏車. A ranking cannot tell a literary reading from the word people say.
 *
 * `tools/taigi-check.ts --level 3` reports how these stand up against the source.
 */
import type { HandRow } from './handAuthored.ts'

export const HSK3_ROWS: readonly HandRow[] = [
    ['啊', '啊', 'ah', 'ah'],
    ['阿姨', '阿姨', 'a-î', 'a-î'],
    ['矮', '矮', 'é', 'é'],
    ['爱好', '興趣', 'hìng-tshù', 'hèng-chhù', 'an interest or hobby is 興趣'],
    ['安静', '安靜', 'an-tsīng', 'an-chēng'],
    ['把', '攑', 'gia̍h', 'gia̍h', 'to hold is 攑; 把 is a classifier for tools'],
    ['搬', '搬', 'puann', 'poaⁿ'],
    ['班', '班', 'pan', 'pan'],
    ['办法', '辦法', 'pān-huat', 'pān-hoat'],
    ['办公室', '辦公室', 'pān-kong-sik', 'pān-kong-sek'],
    ['半', '半', 'puànn', 'pòaⁿ'],
    ['帮忙', '幫忙', 'pang-bâng', 'pang-bâng'],
    ['包', '包', 'pau', 'pau'],
    ['饱', '飽', 'pá', 'pá'],
    ['北方', '北方', 'pak-hong', 'pak-hong'],
    ['被', '予', 'hōo', 'hō͘', 'the passive marker in Taiwanese is 予'],
    ['鼻子', '鼻', 'phīnn', 'phīⁿ'],
    ['比较', '比較', 'pí-kàu', 'pí-kàu'],
    ['比赛', '比賽', 'pí-sài', 'pí-sài'],
    ['笔记本', '筆記本', 'pit-kì-pún', 'pit-kì-pún'],
    ['必须', '必須', 'pit-su', 'pit-su'],
    ['变化', '變化', 'piàn-huà', 'piàn-hòa'],
    ['别人', '別人', 'pa̍t-lâng', 'pa̍t-lâng'],
    ['冰箱', '冰箱', 'ping-siunn', 'peng-siuⁿ'],
    ['不但…而且…', '不但', 'put-tān', 'put-tān'],
    ['菜单', '菜單', 'tshài-tuann', 'chhài-toaⁿ'],
    ['参加', '參加', 'tsham-ka', 'chham-ka'],
    ['草', '草', 'tsháu', 'chháu'],
    ['层', '層', 'tsân', 'chân'],
    ['差', '差', 'tsha', 'chha'],
    ['超市', '超市', 'tshiau-tshī', 'chhiau-chhī'],
    ['衬衫', '襯衫', 'tshìn-sann', 'chhìn-saⁿ'],
    ['城市', '城市', 'siânn-tshī', 'siâⁿ-chhī'],
    ['成绩', '成績', 'sîng-tsik', 'sêng-chek'],
    ['迟到', '遲到', 'tî-tò', 'tî-tò'],
    ['除了', '除了', 'tî-liáu', 'tî-liáu'],
    ['船', '船', 'tsûn', 'chûn'],
    ['春', '春', 'tshun', 'chhun'],
    ['词典', '詞典', 'sû-tián', 'sû-tián'],
    ['聪明', '聰明', 'tshong-bîng', 'chhong-bêng'],
    ['打扫', '打掃', 'tánn-sàu', 'táⁿ-sàu'],
    ['打算', '打算', 'tánn-sǹg', 'táⁿ-sǹg'],
    ['带', '帶', 'tuà', 'tòa'],
    ['担心', '擔心', 'tam-sim', 'tam-sim', 'a literary compound, so 擔 is read tam'],
    ['蛋糕', '雞卵糕', 'ke-nn̄g-ko', 'ke-nn̄g-ko', 'cake is 雞卵糕, from 雞卵 an egg'],
    ['当然', '當然', 'tong-jiân', 'tong-jiân'],
    ['地', '地', 'tē', 'tē', 'the adverbial particle, as in 慢慢仔'],
    ['灯', '燈', 'ting', 'teng'],
    ['地方', '地方', 'tē-hng', 'tē-hng'],
    ['地铁', '地鐵', 'tē-thih', 'tē-thih'],
    ['地图', '地圖', 'tē-tôo', 'tē-tô͘'],
    ['电梯', '電梯', 'tiān-thui', 'tiān-thui'],
    ['电子邮件', '電子郵件', 'tiān-tsú-iû-kiānn', 'tiān-chú-iû-kiāⁿ'],
    ['东', '東', 'tang', 'tang'],
    ['冬', '冬', 'tang', 'tang'],
    ['动物', '動物', 'tōng-bu̍t', 'tōng-bu̍t'],
    ['短', '短', 'té', 'té'],
    ['段', '段', 'tuānn', 'tōaⁿ'],
    ['锻炼', '鍛鍊', 'tuàn-liān', 'toàn-liān'],
    ['多么', '偌', 'luā', 'lōa', 'how, as in 偌爾好'],
    ['饿', '枵', 'iau', 'iau', 'hungry is 枵; 餓 is read gō and is the literary form'],
    ['耳朵', '耳仔', 'hīnn-á', 'hīⁿ-á'],
    ['发', '發', 'huat', 'hoat'],
    ['发烧', '發燒', 'huat-sio', 'hoat-sio'],
    ['发现', '發現', 'huat-hiān', 'hoat-hiān'],
    ['方便', '方便', 'hong-piān', 'hong-piān'],
    ['放', '放', 'pàng', 'pàng'],
    ['放心', '放心', 'hòng-sim', 'hòng-sim'],
    ['分', '分', 'pun', 'pun'],
    ['复习', '複習', 'ho̍k-si̍p', 'ho̍k-si̍p'],
    ['附近', '附近', 'hù-kīn', 'hù-kīn'],
    ['干净', '乾淨', 'kan-tsīng', 'kan-chēng'],
    ['感冒', '感冒', 'kám-mōo', 'kám-mō͘'],
    ['感兴趣', '感興趣', 'kám-hìng-tshù', 'kám-hìng-chhù'],
    ['刚才', '剛才', 'kong-tsâi', 'kong-châi'],
    ['个子', '身長', 'sin-tn̂g', 'sin-tn̂g', 'stature; 個子 is not how Taiwanese says it'],
    ['根据', '根據', 'kin-kì', 'kin-kì'],
    ['跟', '佮', 'kah', 'kah'],
    ['更', '閣較', 'koh-khah', 'koh-khah'],
    ['公斤', '公斤', 'kong-kin', 'kong-kin'],
    ['公园', '公園', 'kong-hn̂g', 'kong-hn̂g'],
    ['故事', '故事', 'kòo-sū', 'kò͘-sū'],
    ['刮风', '起風', 'khí-hong', 'khí-hong'],
    ['关', '關', 'kuainn', 'koaiⁿ'],
    ['关系', '關係', 'kuan-hē', 'koan-hē'],
    ['关心', '關心', 'kuan-sim', 'koan-sim'],
    ['关于', '關於', 'kuan-î', 'koan-î'],
    ['国家', '國家', 'kok-ka', 'kok-ka'],
    ['过', '過', 'kuè', 'kòe'],
    ['过去', '過去', 'kuè-khì', 'kòe-khì'],
    ['还是', '抑是', 'ia̍h-sī', 'ia̍h-sī'],
    ['害怕', '驚', 'kiann', 'kiaⁿ'],
    ['黑板', '黑板', 'hi̍k-pán', 'he̍k-pán'],
    ['后来', '後來', 'āu-lâi', 'āu-lâi'],
    ['护照', '護照', 'hōo-tsiò', 'hō͘-chiò'],
    ['花', '花', 'hue', 'hoe'],
    ['画', '畫', 'uē', 'ōe'],
    ['坏', '歹', 'pháinn', 'pháiⁿ', 'bad is 歹, read pháinn'],
    ['欢迎', '歡迎', 'huan-gîng', 'hoan-gêng'],
    ['环境', '環境', 'khuân-kíng', 'khoân-kéng'],
    ['还', '還', 'hîng', 'hêng', 'to return, as in 還錢'],
    ['换', '換', 'uānn', 'ōaⁿ'],
    ['黄河', '黃河', 'N̂g-hô', 'N̂g-hô'],
    ['回答', '回答', 'huê-tap', 'hôe-tap'],
    ['会议', '會議', 'huē-gī', 'hōe-gī'],
    ['或者', '或者', 'hi̍k-tsiá', 'he̍k-chiá'],
    ['几乎', '幾乎', 'ki-hôo', 'ki-hô͘'],
    ['机会', '機會', 'ki-huē', 'ki-hōe'],
    ['极', '極', 'ki̍k', 'ke̍k'],
    ['季节', '季節', 'kuì-tsiat', 'kùi-chiat'],
    ['记得', '記得', 'kì-tit', 'kì-tit'],
    ['检查', '檢查', 'kiám-tsa', 'kiám-cha'],
    ['简单', '簡單', 'kán-tuann', 'kán-toaⁿ'],
    ['健康', '健康', 'kiān-khong', 'kiān-khong'],
    ['见面', '見面', 'kìnn-bīn', 'kìⁿ-bīn'],
    ['讲', '講解', 'káng-kái', 'káng-kái', 'to explain; plain 講 kóng is already HSK 1 说'],
    ['教', '教', 'kà', 'kà'],
    ['脚', '腳', 'kha', 'kha'],
    ['角', '角', 'kak', 'kak'],
    ['接', '接', 'tsiap', 'chiap'],
    ['街道', '街道', 'ke-tō', 'ke-tō'],
    ['结婚', '結婚', 'kiat-hun', 'kiat-hun'],
    ['结束', '結束', 'kiat-sok', 'kiat-sok'],
    ['节目', '節目', 'tsiat-bo̍k', 'chiat-bo̍k'],
    ['节日', '節日', 'tsiat-ji̍t', 'chiat-ji̍t'],
    ['解决', '解決', 'kái-kuat', 'kái-koat'],
    ['借', '借', 'tsioh', 'chioh'],
    ['经常', '經常', 'king-siông', 'keng-siông'],
    ['经过', '經過', 'king-kuè', 'keng-kòe'],
    ['经理', '經理', 'king-lí', 'keng-lí'],
    ['久', '久', 'kú', 'kú'],
    ['旧', '舊', 'kū', 'kū'],
    ['句子', '句子', 'kù-tsú', 'kù-chú'],
    ['决定', '決定', 'kuat-tīng', 'koat-tēng'],
    ['可爱', '可愛', 'khó-ài', 'khó-ài'],
    ['渴', '喙焦', 'tshuì-ta', 'chhùi-ta', 'thirsty is literally dry-mouthed'],
    ['刻', '刻', 'khik', 'khek'],
    ['客人', '客人', 'kheh-lâng', 'kheh-lâng'],
    ['空调', '冷氣', 'líng-khì', 'léng-khì', 'air conditioning is 冷氣'],
    ['口', '口', 'kháu', 'kháu'],
    ['哭', '哭', 'khàu', 'khàu'],
    ['裤子', '褲', 'khòo', 'khò͘'],
    ['筷子', '箸', 'tī', 'tī', 'chopsticks are 箸'],
    ['蓝', '藍', 'nâ', 'nâ'],
    ['老', '老', 'lāu', 'lāu'],
    ['离开', '離開', 'lī-khui', 'lī-khui'],
    ['礼物', '禮物', 'lé-bu̍t', 'lé-bu̍t'],
    ['历史', '歷史', 'li̍k-sú', 'le̍k-sú'],
    ['脸', '面', 'bīn', 'bīn', 'the face is 面'],
    ['练习', '練習', 'liān-si̍p', 'liān-si̍p'],
    ['辆', '台', 'tâi', 'tâi', 'the classifier for vehicles is 台'],
    ['聊天', '開講', 'khai-káng', 'khai-káng', 'to chat is 開講'],
    ['了解', '了解', 'liáu-kái', 'liáu-kái'],
    ['邻居', '厝邊', 'tshù-pinn', 'chhù-piⁿ', 'a neighbour is the person next door, 厝邊'],
    ['留学', '留學', 'liû-ha̍k', 'liû-ha̍k'],
    ['楼', '樓', 'lâu', 'lâu'],
    ['绿', '綠', 'li̍k', 'le̍k'],
    ['马', '馬', 'bé', 'bé'],
    ['马上', '馬上', 'má-siōng', 'má-siōng'],
    ['满意', '滿意', 'muá-ì', 'móa-ì'],
    ['帽子', '帽子', 'bō-á', 'bō-á'],
    ['米', '米', 'bí', 'bí'],
    ['面包', '麵包', 'mī-pau', 'mī-pau'],
    ['明白', '明白', 'bîng-pi̍k', 'bêng-pe̍k'],
    ['拿', '提', 'the̍h', 'the̍h', 'to hold or take is 提'],
    ['奶奶', '阿媽', 'a-má', 'a-má', 'grandmother is 阿媽'],
    ['南', '南', 'lâm', 'lâm'],
    ['难', '難', 'oh', 'oh', 'difficult is the colloquial reading oh'],
    ['难过', '難過', 'lân-kuè', 'lân-kòe'],
    ['年级', '年級', 'nî-kip', 'nî-kip'],
    ['年轻', '年輕', 'nî-khing', 'nî-kheng'],
    ['鸟', '鳥', 'tsiáu', 'chiáu'],
    ['努力', '努力', 'lóo-li̍k', 'ló͘-le̍k'],
    ['爬山', '爬山', 'pê-suann', 'pê-soaⁿ'],
    ['盘子', '盤子', 'puânn-á', 'pôaⁿ-á'],
    ['胖', '肥', 'puî', 'pûi', 'fat is 肥'],
    ['啤酒', '啤酒', 'pî-tsiú', 'pî-chiú'],
    ['皮鞋', '皮鞋', 'phuê-ê', 'phôe-ê'],
    ['瓶子', '矸仔', 'kan-á', 'kan-á', 'a bottle is 矸仔'],
    ['其实', '其實', 'kî-si̍t', 'kî-si̍t'],
    ['其他', '其他', 'kî-tha', 'kî-tha'],
    ['奇怪', '奇怪', 'kî-kuài', 'kî-koài'],
    ['骑', '騎', 'khiâ', 'khiâ'],
    ['起飞', '起飛', 'khí-pue', 'khí-poe'],
    ['起来', '起來', 'khí-lâi', 'khí-lâi'],
    ['清楚', '清楚', 'tshing-tshóo', 'chheng-chhó͘'],
    ['请假', '請假', 'tshíng-kà', 'chhéng-kà'],
    ['秋', '秋', 'tshiu', 'chhiu'],
    ['裙子', '裙', 'kûn', 'kûn'],
    ['然后', '然後', 'jiân-āu', 'jiân-āu'],
    ['热情', '熱情', 'jia̍t-tsîng', 'jia̍t-chêng'],
    ['认为', '認為', 'jīn-uî', 'jīn-ûi'],
    ['认真', '認真', 'jīn-tsin', 'jīn-chin'],
    ['容易', '容易', 'iông-ī', 'iông-ī'],
    ['如果', '若是', 'nā-sī', 'nā-sī', 'if is 若是'],
    ['伞', '傘', 'suànn', 'sòaⁿ'],
    ['上网', '上網', 'siōng-bāng', 'siōng-bāng'],
    ['声音', '聲音', 'siann-im', 'siaⁿ-im'],
    ['生气', '受氣', 'siū-khì', 'siū-khì', 'to be angry is 受氣'],
    ['世界', '世界', 'sè-kài', 'sè-kài'],
    ['试', '試', 'tshì', 'chhì'],
    ['瘦', '瘦', 'sán', 'sán'],
    ['叔叔', '阿叔', 'a-tsik', 'a-chek'],
    ['舒服', '舒服', 'su-ho̍k', 'su-ho̍k'],
    ['数学', '數學', 'sòo-ha̍k', 'sò͘-ha̍k'],
    ['树', '樹', 'tshiū', 'chhiū'],
    ['刷牙', '洗喙', 'sé-tshuì', 'sé-chhùi', 'to brush teeth is literally to wash the mouth'],
    ['双', '雙', 'siang', 'siang'],
    ['水平', '水平', 'tsuí-pîng', 'chúi-pêng'],
    ['司机', '司機', 'su-ki', 'su-ki'],
    ['太阳', '日頭', 'ji̍t-thâu', 'ji̍t-thâu', 'the sun is 日頭'],
    ['特别', '特別', 'ti̍k-pi̍t', 'te̍k-pia̍t'],
    ['疼', '疼', 'thiànn', 'thiàⁿ'],
    ['提高', '提高', 'thê-ko', 'thê-ko'],
    ['体育', '體育', 'thé-io̍k', 'thé-io̍k'],
    ['甜', '甜', 'tinn', 'tiⁿ'],
    ['条', '條', 'tiâu', 'tiâu'],
    ['同事', '同事', 'tông-sū', 'tông-sū'],
    ['同意', '同意', 'tông-ì', 'tông-ì'],
    ['头发', '頭毛', 'thâu-mn̂g', 'thâu-mn̂g', 'hair is 頭毛'],
    ['突然', '突然', 'tu̍t-jiân', 'tu̍t-jiân'],
    ['图书馆', '圖書館', 'tôo-su-kuán', 'tô͘-su-koán'],
    ['腿', '腿', 'thuí', 'thúi'],
    ['完成', '完成', 'uân-sîng', 'oân-sêng'],
    ['碗', '碗', 'uánn', 'oáⁿ'],
    ['万', '萬', 'bān', 'bān'],
    ['忘记', '忘記', 'bōng-kì', 'bōng-kì'],
    ['为', '因為', 'in-uī', 'in-ūi', 'because of; 為了 below takes the other form'],
    ['为了', '為著', 'uī-tio̍h', 'ūi-tio̍h', 'in order to'],
    ['位', '位', 'uī', 'ūi'],
    ['文化', '文化', 'bûn-huà', 'bûn-hòa'],
    ['西', '西', 'sai', 'sai'],
    ['习惯', '習慣', 'si̍p-kuàn', 'si̍p-koàn'],
    ['洗手间', '便所', 'piān-sóo', 'piān-só͘', 'the toilet is 便所'],
    ['洗澡', '洗身軀', 'sé-sin-khu', 'sé-sin-khu', 'to bathe is to wash the body'],
    ['夏', '夏', 'hā', 'hā'],
    ['先', '先', 'sing', 'seng'],
    ['相信', '相信', 'siong-sìn', 'siong-sìn'],
    ['香蕉', '香蕉', 'king-tsio', 'keng-chio'],
    ['像', '像', 'tshiūnn', 'chhiūⁿ'],
    ['向', '向', 'hiòng', 'hiòng'],
    ['小心', '小心', 'sió-sim', 'sió-sim'],
    ['校长', '校長', 'hāu-tiúnn', 'hāu-tiúⁿ'],
    ['新闻', '新聞', 'sin-bûn', 'sin-bûn'],
    ['新鲜', '新鮮', 'sin-sian', 'sin-sian'],
    ['信用卡', '信用卡', 'sìn-iōng-khah', 'sìn-iōng-khah'],
    ['行李箱', '行李箱', 'hîng-lí-siunn', 'hêng-lí-siuⁿ'],
    ['熊猫', '貓熊', 'niau-hîm', 'niau-hîm', 'Taiwan says 貓熊 rather than 熊貓'],
    ['需要', '需要', 'su-iàu', 'su-iàu'],
    ['选择', '選擇', 'suán-ti̍k', 'soán-te̍k'],
    ['要求', '要求', 'iau-kiû', 'iau-kiû'],
    ['爷爷', '阿公', 'a-kong', 'a-kong', 'grandfather is 阿公'],
    ['一直', '一直', 'it-ti̍t', 'it-ti̍t'],
    ['一定', '一定', 'it-tīng', 'it-tēng'],
    ['一共', '一共', 'it-kiōng', 'it-kiōng'],
    ['一会儿', '一下仔', 'tsi̍t-ē-á', 'chi̍t-ē-á'],
    ['一样', '一樣', 'tsi̍t-iūnn', 'chi̍t-iūⁿ'],
    ['以前', '以前', 'í-tsîng', 'í-chêng'],
    ['一般', '一般', 'it-puann', 'it-poaⁿ'],
    ['一边', '一邊', 'tsi̍t-pinn', 'chi̍t-piⁿ'],
    ['音乐', '音樂', 'im-ga̍k', 'im-ga̍k'],
    ['银行', '銀行', 'gûn-hâng', 'gûn-hâng'],
    ['饮料', '飲料', 'ím-liāu', 'ím-liāu'],
    ['应该', '應該', 'ing-kai', 'eng-kai'],
    ['影响', '影響', 'íng-hióng', 'éng-hióng'],
    ['用', '用', 'iōng', 'iōng'],
    ['游戏', '遊戲', 'iû-hì', 'iû-hì'],
    ['有名', '有名', 'ū-miâ', 'ū-miâ'],
    ['又', '又', 'iū', 'iū'],
    ['遇到', '拄著', 'tú-tio̍h', 'tú-tio̍h', 'to run into someone is 拄著'],
    ['元', '元', 'guân', 'goân'],
    ['愿意', '願意', 'guān-ì', 'goān-ì'],
    ['月亮', '月娘', 'gue̍h-niû', 'goe̍h-niû', 'the moon is 月娘'],
    ['越', '越', 'ua̍t', 'oa̍t'],
    ['站', '站', 'tsām', 'chām'],
    ['张', '張', 'tiunn', 'tiuⁿ'],
    ['长', '長', 'tióng', 'tióng', 'elder; the HSK 2 长 long is tn̂g'],
    ['着急', '著急', 'tio̍h-kip', 'tio̍h-kip'],
    ['照顾', '照顧', 'tsiàu-kòo', 'chiàu-kò͘'],
    ['照片', '照片', 'tsiàu-phìnn', 'chiàu-phìⁿ'],
    ['照相机', '照相機', 'tsiàu-siōng-ki', 'chiàu-siōng-ki'],
    ['只', '只', 'tsí', 'chí'],
    ['只有…才…', '只有', 'tsí-ū', 'chí-ū'],
    ['中间', '中間', 'tiong-king', 'tiong-keng'],
    ['中文', '中文', 'tiong-bûn', 'tiong-bûn'],
    ['终于', '終於', 'tsiong-î', 'chiong-î'],
    ['种', '種', 'tsíng', 'chéng'],
    ['重要', '重要', 'tiōng-iàu', 'tiōng-iàu'],
    ['周末', '週末', 'tsiu-bua̍t', 'chiu-boa̍t'],
    ['主要', '主要', 'tsú-iàu', 'chú-iàu'],
    ['注意', '注意', 'tsù-ì', 'chù-ì'],
    ['自己', '自己', 'tsū-kí', 'chū-kí'],
    ['自行车', '跤踏車', 'kha-ta̍h-tshia', 'kha-ta̍h-chhia', 'a bicycle is 跤踏車'],
    ['总是', '總是', 'tsóng-sī', 'chóng-sī'],
    ['嘴', '嘴', 'tshuì', 'chhùi'],
    ['最后', '最後', 'tsuè-āu', 'chòe-āu'],
    ['最近', '最近', 'tsuè-kīn', 'chòe-kīn'],
    ['作业', '作業', 'tsok-gia̍p', 'chok-gia̍p'],
]
