/**
 * Hand-authored Taiwanese forms for the HSK 2 vocabulary.
 *
 * HSK 1 was produced by ranking candidate rows and then correcting the ranking, which works
 * because the ranking is right most of the time. This level is the other way round: every form
 * below was chosen by hand first, and the source is then used to check it. The reason is that
 * HSK 2 is where the literary/colloquial split stops being an occasional trap and becomes the
 * norm - the everyday Taiwanese word is often not the character in front of you at all, and a
 * ranking has no way to know that 走 means "to run" in Taiwanese and 行 means "to walk".
 *
 * So these are answers, not guesses. `fromSource` is false for all of them, and the entries in
 * `taiwaneseOverrides.ts` carry that through so a reviewer can tell them apart from the HSK 1
 * corrections that were merely pickings from the source.
 *
 * The row shape and the romanisation conventions are documented on `HandRow`.
 */
import type { HandRow } from './handAuthored.ts'

export const HSK2_ROWS: readonly HandRow[] = [
    ['吧', '啦', 'là', 'là', 'Taiwanese has no 吧; the suggestion particle is 啦'],
    ['白', '白', 'pe̍h', 'pe̍h'],
    ['百', '百', 'pah', 'pah'],
    ['帮助', '幫贊', 'pang-tsān', 'pang-chān'],
    ['报纸', '報紙', 'pò-tsuá', 'pò-chóa'],
    ['比', '比', 'pí', 'pí'],
    ['别', '莫', 'mài', 'mài', "negative imperative; 別 is read pat but never means 'do not'"],
    ['宾馆', '賓館', 'pin-kuán', 'pin-koán', 'the source equivalent; 旅館 lú-kuán is also current'],
    ['长', '長', 'tn̂g', 'tn̂g', 'the extract holds only the literary readings tiông/tióng/tshiâng'],
    ['唱歌', '唱歌', 'tshiùnn-kua', 'chhiùⁿ-koa'],
    ['出', '出', 'tshut', 'chhut'],
    ['穿', '穿', 'tshīng', 'chhēng'],
    ['次', '擺', 'pái', 'pái', 'the classifier for occurrences is 擺, not 次'],
    ['从', '由', 'iû', 'iû', "由 rather than 對, which is already the answer for 对"],
    ['错', '錯', 'tshò', 'chhò'],
    ['打篮球', '拍籃球', 'phah-nâ-kiû', 'phah-nâ-kiû', 'Taiwanese plays ball with the hand 拍, not 打'],
    ['大家', '逐家', 'ta̍k-ke', 'ta̍k-ke'],
    ['到', '到', 'kàu', 'kàu'],
    ['得', '甲', 'kah', 'kah', 'the degree particle is 甲 kah'],
    ['等', '等', 'tán', 'tán'],
    ['弟弟', '小弟', 'sió-tī', 'sió-tī'],
    ['第一', '第一', 'tē-it', 'tē-it'],
    ['懂', '了解', 'liáu-kái', 'liáu-kái'],
    ['对', '對', 'tuì', 'tùi'],
    ['房间', '房間', 'pâng-king', 'pâng-keng'],
    ['非常', '非常', 'hui-siông', 'hui-siông'],
    ['服务员', '服務員', 'ho̍k-bū-uân', 'ho̍k-bū-oân'],
    ['高', '懸', 'kuân', 'koân', 'the colloquial word for tall is 懸, not a reading of 高'],
    ['告诉', '講', 'kóng', 'kóng', 'the same word as HSK 1 说; Taiwanese does not split them'],
    ['哥哥', '阿兄', 'a-hiann', 'a-hiaⁿ'],
    ['给', '予', 'hōo', 'hō͘'],
    ['公共汽车', '公車', 'kong-tshia', 'kong-chhia'],
    ['公司', '公司', 'kong-si', 'kong-si'],
    ['贵', '貴', 'kuì', 'kùi'],
    ['过', '過', 'kuè', 'kòe', 'the experiential suffix; the source gives kuè, unmarked for tone'],
    ['孩子', '囡仔', 'gín-á', 'gín-á'],
    ['还', '猶', 'iáu', 'iáu'],
    ['好吃', '好食', 'hó-tsia̍h', 'hó-chia̍h', 'Taiwanese eats with 食, not 吃'],
    ['黑', '烏', 'oo', 'o͘', 'black is 烏; 黑 is read hik and barely used'],
    ['红', '紅', 'âng', 'âng'],
    ['火车站', '火車站', 'hué-tshia-tsām', 'hóe-chhia-chām'],
    ['机场', '機場', 'ki-tiûnn', 'ki-tiûⁿ'],
    ['鸡蛋', '雞卵', 'ke-nn̄g', 'ke-nn̄g', 'an egg is 雞卵, not 雞蛋'],
    ['件', '件', 'kiānn', 'kiāⁿ'],
    ['教室', '教室', 'kàu-sik', 'kàu-sek'],
    ['姐姐', '阿姊', 'a-tsí', 'a-chí'],
    ['介绍', '紹介', 'siāu-kài', 'siāu-kài', 'Taiwanese keeps the older 紹介 order'],
    ['近', '近', 'kīn', 'kīn'],
    ['进', '入', 'ji̍p', 'ji̍p'],
    ['就', '就', 'tsiū', 'chiū'],
    ['觉得', '感覺', 'kám-kak', 'kám-kak'],
    ['咖啡', '咖啡', 'ka-pi', 'ka-pi'],
    ['开始', '開始', 'khai-sí', 'khai-sí'],
    ['考试', '考試', 'khó-tshì', 'khó-chhì'],
    ['可能', '可能', 'khó-lîng', 'khó-lêng'],
    ['可以', '會使', 'ē-sái', 'ē-sái'],
    ['课', '課', 'khò', 'khò'],
    ['快', '緊', 'kín', 'kín', 'quick is 緊; 快 is read khuài and means pleasant'],
    ['快乐', '快樂', 'khuài-lo̍k', 'khòai-lo̍k'],
    ['累', '忝', 'thiám', 'thiám'],
    ['离', '離', 'lī', 'lī'],
    ['两', '兩', 'nn̄g', 'nn̄g'],
    ['零', '零', 'lîng', 'lêng'],
    ['路', '路', 'lōo', 'lō͘'],
    ['旅游', '旅遊', 'lí-iû', 'lí-iû'],
    ['卖', '賣', 'bē', 'bē'],
    ['慢', '慢', 'bān', 'bān'],
    ['忙', '無閒', 'bô-îng', 'bô-êng', 'busy is literally "no leisure"'],
    ['每', '每', 'muí', 'muí'],
    ['妹妹', '小妹', 'sió-muē', 'sió-mōe'],
    ['门', '門', 'mn̂g', 'mn̂g'],
    ['面条', '麵條', 'mī-tiâu', 'mī-tiâu'],
    ['男', '男', 'lâm', 'lâm'],
    ['您', '您', 'lín', 'lín'],
    ['牛奶', '牛奶', 'gû-ling', 'gû-leng'],
    ['女', '女', 'lú', 'lú'],
    ['旁边', '邊仔', 'pinn-á', 'piⁿ-á'],
    ['跑步', '走', 'tsáu', 'cháu', '跑步 is 走; 走 itself is 行, the classic false friend'],
    ['便宜', '俗', 'sio̍k', 'sio̍k', 'cheap is 俗 "common"; 便宜 is read pián-gî and sounds like Mandarin'],
    ['票', '票', 'phiò', 'phiò'],
    ['妻子', '某', 'bóo', 'bó͘'],
    ['起床', '起床', 'khí-tshn̂g', 'khí-chhn̂g'],
    ['千', '千', 'tshing', 'chheng'],
    ['铅笔', '鉛筆', 'iân-pit', 'iân-pit'],
    ['晴', '晴', 'tsînn', 'chîⁿ'],
    ['去年', '舊年', 'kū-nî', 'kū-nî', 'last year is 舊年 "the old year"'],
    ['让', '允准', 'ín-tsún', 'ín-chún', '予 would be the natural gloss but is already 给'],
    ['日', '日', 'ji̍t', 'ji̍t'],
    ['上班', '上班', 'siōng-pan', 'siōng-pan', 'the source also lists siāng-pan'],
    ['身体', '身軀', 'sin-khu', 'sin-khu', 'the source also lists sing-khu'],
    ['生病', '破病', 'phuà-pēnn', 'phòa-pēⁿ', 'falling ill is 破病 "broken by illness"'],
    ['生日', '生日', 'senn-ji̍t', 'seⁿ-ji̍t'],
    ['时间', '時間', 'sî-kan', 'sî-kan'],
    ['事情', '代誌', 'tāi-tsì', 'tāi-chì', 'the everyday word for a matter is 代誌'],
    ['手表', '手錶', 'tshiú-pió', 'chhiú-pió'],
    ['手机', '手機', 'tshiú-ki', 'chhiú-ki'],
    ['说话', '講話', 'kóng-uē', 'kóng-ōe'],
    ['送', '送', 'sàng', 'sàng'],
    ['虽然…但是…', '雖然', 'sui-jiân', 'sui-jiân', 'Taiwanese uses 雖然 with 但是'],
    ['它', '伊', 'i', 'i', 'Taiwanese has one third-person pronoun for people and things'],
    ['踢足球', '踢足球', 'that-tsiok-kiû', 'that-chiok-kiû'],
    ['题', '題', 'tê', 'tê'],
    ['跳舞', '跳舞', 'thiàu-bú', 'thiàu-bú'],
    ['外', '外', 'guā', 'gōa'],
    ['完', '完', 'uân', 'oân'],
    ['玩', '耍', 'sńg', 'sńg', 'to play is 耍, not 玩'],
    ['晚上', '暗時', 'àm-sî', 'àm-sî'],
    ['往', '往', 'óng', 'óng'],
    ['为什么', '為啥物', 'uī-siánn-mi̍h', 'ūi-siáⁿ-mi̍h'],
    ['问', '問', 'mn̄g', 'mn̄g'],
    ['问题', '問題', 'būn-tê', 'būn-tê'],
    ['希望', '希望', 'hi-bāng', 'hi-bāng'],
    ['西瓜', '西瓜', 'si-kue', 'si-koe'],
    ['洗', '洗', 'sé', 'sé'],
    ['小时', '點鐘', 'tiám-tsing', 'tiám-cheng', 'an hour is 點鐘 "a clock point"'],
    ['笑', '笑', 'tshiò', 'chhiò'],
    ['新', '新', 'sin', 'sin'],
    ['姓', '姓', 'sìnn', 'sìⁿ'],
    ['休息', '休息', 'hiu-sik', 'hiu-sek'],
    ['雪', '雪', 'seh', 'seh'],
    ['颜色', '顏色', 'gân-sik', 'gân-sek'],
    ['眼睛', '目睭', 'ba̍k-tsiu', 'ba̍k-chiu', 'the eye is 目睭, never 眼睛'],
    ['羊肉', '羊肉', 'iûnn-bah', 'iûⁿ-bah', 'meat is 肉 bah'],
    ['药', '藥仔', 'io̍h-á', 'io̍h-á'],
    ['要', '欲', 'beh', 'beh', 'to want is 欲, read beh'],
    ['也', '也', 'iā', 'iā'],
    ['一下', '一下', 'tsi̍t-ē', 'chi̍t-ē'],
    ['已经', '已經', 'í-king', 'í-keng'],
    ['一起', '做伙', 'tsò-hué', 'chò-hóe', 'together is 做伙, not 一起'],
    ['意思', '意思', 'ì-sù', 'ì-sù'],
    ['因为…所以…', '因為', 'in-uī', 'in-uī'],
    ['阴', '陰', 'im', 'im', 'the source row is iam; the weather word is 烏陰 oo-im'],
    ['游泳', '泅水', 'siû-tsuí', 'siû-chúi', 'to swim is 泅水 "to float on water"'],
    ['右边', '正手爿', 'tsiànn-tshiú-pîng', 'chiàⁿ-chhiú-pêng', 'the right hand side'],
    ['鱼', '魚', 'hî', 'hî'],
    ['远', '遠', 'hn̄g', 'hn̄g'],
    ['运动', '運動', 'ūn-tōng', 'ūn-tōng'],
    ['再', '閣', 'koh', 'koh', 'again is usually the adverb 閣'],
    ['早上', '早起', 'tsá-khí', 'chá-khí'],
    ['丈夫', '翁', 'ang', 'ang', 'a husband is 翁, a wife is 某'],
    ['找', '揣', 'tshuē', 'chhōe', 'to look for is 揣, not 找'],
    ['着', '著', 'tio̍h', 'tio̍h', 'the result particle; the source writes it without the neutral marker'],
    ['真', '真', 'tsin', 'chin'],
    ['正在', '佇咧', 'tī-leh', 'tī-leh', 'the progressive marker'],
    ['知道', '知影', 'tsai-iánn', 'chai-iáⁿ', 'to know is 知影'],
    ['准备', '準備', 'tsún-pī', 'chún-pī'],
    ['走', '行', 'kiânn', 'kiâⁿ', 'to walk is 行; see 跑步 above'],
    ['最', '上', 'siōng', 'siōng', 'the superlative is 上 (上好 "the best")'],
    ['左边', '倒手爿', 'tò-tshiú-pîng', 'tò-chhiú-pêng', 'the left hand side, literally the reversed hand'],
]
