/**
 * Hand-authored Taiwanese forms for the HSK 5 vocabulary, part one of five.
 *
 * Written by hand for the same reason as HSK 2 to 4: the reading is the thing worth capturing, and
 * a character match lists the literary form first about as often as the everyday one. 呆 is `gōng`,
 * 淡 is `chiáⁿ`, 凍 is `tàng`, 拆 is `thiah` - same word, different sound, which is precisely what a
 * learner needs and precisely what the ranking will not tell them.
 *
 * `tools/taigi-check.ts --level 5` reports how these stand up against the source and how far the
 * mechanical ranking would have been from them.
 */
import type { HandRow } from './handAuthored.ts'

export const HSK5_ROWS_A: readonly HandRow[] = [
    ['哎', '哎', 'ai', 'ai'],
    ['唉', '唉', 'ai', 'ai'],
    ['爱护', '愛護', 'ài-hōo', 'ài-hō͘'],
    ['爱惜', '愛惜', 'ài-sioh', 'ài-sioh'],
    ['爱心', '愛心', 'ài-sim', 'ài-sim'],
    ['安慰', '安慰', 'an-uì', 'an-ùi'],
    ['安装', '安裝', 'an-tsong', 'an-chong'],
    ['岸', '岸', 'huānn', 'hōaⁿ'],
    ['暗', '暗', 'àm', 'àm'],
    ['熬夜', '熬夜', 'gô-iā', 'gô-iā', 'a second reference and the extract both read 熬 as go, not gâu'],
    ['把握', '把握', 'pá-ak', 'pá-ak'],
    ['摆', '擺', 'pái', 'pái'],
    ['办理', '辦理', 'pān-lí', 'pān-lí'],
    ['傍晚', '下晡', 'ē-poo', 'ē-po͘', 'the evening is 下晡; 暗時 is taken by 晚上'],
    ['包裹', '包裹', 'pau-kó', 'pau-kó'],
    ['包含', '包含', 'pau-hâm', 'pau-hâm'],
    ['包括', '包括', 'pau-kuat', 'pau-koat'],
    ['薄', '薄', 'po̍h', 'po̍h', 'thin is the colloquial reading po̍h'],
    ['保持', '保持', 'pó-tshî', 'pó-chhî'],
    ['保存', '保存', 'pó-tsûn', 'pó-chûn'],
    ['保留', '保留', 'pó-liû', 'pó-liû'],
    ['保险', '保險', 'pó-hiám', 'pó-hiám'],
    ['宝贝', '寶貝', 'pó-puè', 'pó-pòe'],
    ['宝贵', '寶貴', 'pó-kuì', 'pó-kùi'],
    ['报到', '報到', 'pò-tàu', 'pò-tàu'],
    ['报道', '報道', 'pò-tō', 'pò-tō'],
    ['报告', '報告', 'pò-kò', 'pò-kò'],
    ['报社', '報社', 'pò-siā', 'pò-siā'],
    ['抱怨', '抱怨', 'phō-uàn', 'phō-oàn'],
    ['悲观', '悲觀', 'pi-kuan', 'pi-koan'],
    ['背', '背', 'puē', 'pōe'],
    ['背景', '背景', 'puē-kíng', 'pōe-kéng'],
    ['被子', '棉被', 'mî-phuē', 'mî-phōe', 'a quilt is 棉被'],
    ['本科', '本科', 'pún-kho', 'pún-kho'],
    ['本领', '本領', 'pún-líng', 'pún-léng'],
    ['本质', '本質', 'pún-tsit', 'pún-chit'],
    ['彼此', '彼此', 'pí-tshú', 'pí-chhú'],
    ['比例', '比例', 'pí-lē', 'pí-lē'],
    ['必然', '必然', 'pit-jiân', 'pit-jiân'],
    ['必要', '必要', 'pit-iàu', 'pit-iàu'],
    ['毕竟', '畢竟', 'pit-kìng', 'pit-kèng'],
    ['避免', '避免', 'pī-bián', 'pī-bián'],
    ['编辑', '編輯', 'pian-tsi̍p', 'pian-chi̍p'],
    ['鞭炮', '鞭炮', 'pian-phàu', 'pian-phàu'],
    ['便', '便', 'piān', 'piān'],
    ['辩论', '辯論', 'piān-lūn', 'piān-lūn'],
    ['标点', '標點', 'phiau-tiám', 'phiau-tiám'],
    ['标志', '標誌', 'phiau-tsì', 'phiau-chì'],
    ['表达', '表達', 'piáu-ta̍t', 'piáu-ta̍t'],
    ['表面', '表面', 'piáu-bīn', 'piáu-bīn'],
    ['表明', '表明', 'piáu-bîng', 'piáu-bêng'],
    ['表情', '表情', 'piáu-tsîng', 'piáu-chêng'],
    ['表现', '表現', 'piáu-hiān', 'piáu-hiān'],
    ['冰激凌', '冰淇淋', 'ping-kî-lîm', 'peng-kî-lîm', 'Taiwan says 冰淇淋'],
    ['病毒', '病毒', 'pēnn-to̍k', 'pēⁿ-to̍k'],
    ['播放', '播放', 'pòo-hòng', 'pò͘-hòng'],
    ['玻璃', '玻璃', 'po-lê', 'po-lê'],
    ['博物馆', '博物館', 'phok-bu̍t-kuán', 'phok-bu̍t-koán'],
    ['脖子', '頷頸', 'ām-kún', 'ām-kún', 'the neck is 頷頸'],
    ['不断', '不斷', 'put-tuān', 'put-toān'],
    ['不见得', '無一定', 'bô-it-tīng', 'bô-it-tēng', 'not necessarily is 無一定'],
    ['不耐烦', '無耐心', 'bô-nāi-sim', 'bô-nāi-sim', 'impatience is 無耐心'],
    ['不要紧', '無要緊', 'bô-iàu-kín', 'bô-iàu-kín', 'it does not matter is 無要緊'],
    ['补充', '補充', 'póo-tshiong', 'pó͘-chhiong'],
    ['不安', '不安', 'put-an', 'put-an'],
    ['不得了', '不得了', 'put-tik-liáu', 'put-tek-liáu'],
    ['不然', '若無', 'nā-bô', 'nā-bô', 'otherwise is 若無'],
    ['不如', '不如', 'put-jû', 'put-jû'],
    ['不足', '不足', 'put-tsiok', 'put-chiok'],
    ['布', '布', 'pòo', 'pò͘'],
    ['步骤', '步驟', 'pōo-tsōo', 'pō͘-chō͘'],
    ['部门', '部門', 'pōo-bûn', 'pō͘-bûn'],
    ['财产', '財產', 'tsâi-sán', 'châi-sán'],
    ['彩虹', '彩虹', 'tshái-khīng', 'chhái-khēng'],
    ['踩', '踏', 'ta̍h', 'ta̍h', 'to step on is 踏'],
    ['采访', '採訪', 'tshái-hóng', 'chhái-hóng'],
    ['采取', '採取', 'tshái-tshú', 'chhái-chhú'],
    ['参考', '參考', 'tsham-khó', 'chham-khó'],
    ['参与', '參與', 'tsham-ú', 'chham-ú'],
    ['惭愧', '慚愧', 'tshâm-khuì', 'chhâm-khuì'],
    ['操场', '操場', 'tshau-tiûnn', 'chhau-tiûⁿ'],
    ['操心', '操心', 'tshau-sim', 'chhau-sim'],
    ['册', '冊', 'tsheh', 'chheh'],
    ['测验', '測驗', 'tshik-giām', 'chhek-giām'],
    ['曾经', '曾經', 'tsing-king', 'cheng-keng'],
    ['叉子', '叉仔', 'tshe-á', 'chhe-á'],
    ['差距', '差距', 'tsha-kū', 'chha-kū'],
    ['插', '插', 'tshah', 'chhah'],
    ['拆', '拆', 'thiah', 'thiah', 'to tear open is the colloquial reading thiah'],
    ['产品', '產品', 'sán-phín', 'sán-phín'],
    ['产生', '產生', 'sán-sing', 'sán-seng'],
    ['常识', '常識', 'siông-sik', 'siông-sek'],
    ['长途', '長途', 'tn̂g-tôo', 'tn̂g-tô͘'],
    ['抄', '抄', 'tshau', 'chhau'],
    ['超级', '超級', 'tshiau-kip', 'chhiau-kip'],
    ['朝', '朝', 'tiâu', 'tiâu'],
    ['潮湿', '潮溼', 'tiau-sip', 'tiau-sip'],
    ['吵', '吵', 'tshá', 'chhá'],
    ['吵架', '冤家', 'uan-ke', 'oan-ke', 'to quarrel is 冤家'],
    ['炒', '炒', 'tshá', 'chhá'],
    ['车库', '車庫', 'tshia-khòo', 'chhia-khò͘'],
    ['车厢', '車廂', 'tshia-siunn', 'chhia-siuⁿ'],
    ['彻底', '徹底', 'thiat-té', 'thiat-té'],
    ['沉默', '恬恬', 'tiām-tiām', 'tiām-tiām', 'silent is 恬恬'],
    ['趁', '趁', 'thàn', 'thàn'],
    ['称', '稱', 'tshìn', 'chhìn'],
    ['称呼', '稱呼', 'tshing-hoo', 'chheng-ho͘'],
    ['称赞', '稱讚', 'tshing-tsàn', 'chheng-chàn'],
    ['成分', '成分', 'sîng-hūn', 'sêng-hūn'],
    ['成果', '成果', 'sîng-kó', 'sêng-kó'],
    ['成就', '成就', 'sîng-tsiū', 'sêng-chiū'],
    ['成立', '成立', 'sîng-li̍p', 'sêng-li̍p'],
    ['成人', '成人', 'sîng-jîn', 'sêng-jîn'],
    ['成熟', '成熟', 'sîng-si̍k', 'sêng-se̍k'],
    ['成语', '成語', 'sîng-gí', 'sêng-gí'],
    ['成长', '成長', 'sîng-tióng', 'sêng-tióng'],
    ['承担', '承擔', 'sîng-tann', 'sêng-taⁿ'],
    ['承认', '承認', 'sîng-jīn', 'sêng-jīn'],
    ['承受', '承受', 'sîng-siū', 'sêng-siū'],
    ['程度', '程度', 'tîng-tōo', 'têng-tō͘'],
    ['程序', '程序', 'tîng-sū', 'têng-sū'],
    ['诚恳', '誠懇', 'sîng-khún', 'sêng-khún'],
    ['吃亏', '食虧', 'tsia̍h-khui', 'chia̍h-khui', 'to suffer a loss is 食虧'],
    ['持续', '持續', 'tshî-sio̍k', 'chhî-sio̍k'],
    ['池塘', '池塘', 'tî-tn̂g', 'tî-tn̂g'],
    ['迟早', '早慢', 'tsá-bān', 'chá-bān', 'sooner or later is 早慢'],
    ['尺子', '尺', 'tshioh', 'chhioh'],
    ['翅膀', '翼', 'si̍t', 'si̍t', 'a wing is 翼'],
    ['充电器', '充電器', 'tshiong-tiān-khì', 'chhiong-tiān-khì'],
    ['充分', '充分', 'tshiong-hun', 'chhiong-hun'],
    ['充满', '充滿', 'muá', 'móa'],
    ['冲', '衝', 'tshiong', 'chhiong'],
    ['重复', '重複', 'tîng-ho̍k', 'têng-ho̍k'],
    ['宠物', '寵物', 'thióng-bu̍t', 'thióng-bu̍t'],
    ['抽屉', '屜仔', 'thuah-á', 'thoah-á', 'a drawer is 屜仔'],
    ['抽象', '抽象', 'thiu-siōng', 'thiu-siōng'],
    ['丑', '醜', 'tshiú', 'chhiú'],
    ['臭', '臭', 'tshàu', 'chhàu'],
    ['出版', '出版', 'tshut-pán', 'chhut-pán'],
    ['出口', '出口', 'tshut-kháu', 'chhut-kháu'],
    ['出色', '出色', 'tshut-sik', 'chhut-sek'],
    ['出示', '出示', 'tshut-sī', 'chhut-sī'],
    ['出席', '出席', 'tshut-si̍k', 'chhut-se̍k'],
    ['初级', '初級', 'tshoo-kip', 'chho͘-kip'],
    ['除非', '除非', 'tû-hui', 'tû-hui'],
    ['除夕', '除夕', 'tû-si̍k', 'tû-se̍k'],
    ['处理', '處理', 'tshú-lí', 'chhú-lí'],
    ['传播', '傳播', 'thuân-pòo', 'thoân-pò͘'],
    ['传染', '傳染', 'thuân-jiám', 'thoân-jiám'],
    ['传说', '傳說', 'thuân-suat', 'thoân-soat'],
    ['传统', '傳統', 'thuân-thóng', 'thoân-thóng'],
    ['窗帘', '窗簾', 'thang-lî', 'thang-lî'],
    ['闯', '闖', 'tshuàng', 'chhoàng'],
    ['创造', '創造', 'tshòng-tsō', 'chhòng-chō'],
    ['吹', '吹', 'tshue', 'chhoe'],
    ['词汇', '詞彙', 'sû-huī', 'sû-huī'],
    ['辞职', '辭職', 'sû-tsit', 'sû-chit'],
    ['此外', '此外', 'tshú-guā', 'chhú-gōa'],
    ['刺激', '刺激', 'tshì-kik', 'chhì-kek'],
    ['次要', '次要', 'tshù-iàu', 'chhù-iàu'],
    ['匆忙', '匆忙', 'tshong-bông', 'chhong-bông'],
    ['从此', '從此', 'tsiông-tshú', 'chiông-chhú', '從 is tsiông here, as the extract has it in 自從'],
    ['从而', '從而', 'tsiông-jî', 'chiông-jî', '從 is tsiông here, as the extract has it in 自從'],
    ['从前', '從前', 'tsiông-tsiân', 'chiông-chiân', 'the extract carries this word outright'],
    ['从事', '從事', 'tsiông-sū', 'chiông-sū', '從 is tsiông here, as the extract has it in 自從'],
    ['粗糙', '粗糙', 'tshoo-tshò', 'chho͘-chhò'],
    ['促进', '促進', 'tshiok-tsìn', 'chhiok-chìn'],
    ['促使', '促使', 'tshiok-sú', 'chhiok-sú'],
    ['醋', '醋', 'tshòo', 'chhò͘'],
    ['催', '催', 'tshui', 'chhui'],
    ['存在', '存在', 'tsûn-tsāi', 'chûn-chāi'],
    ['措施', '措施', 'tshò-si', 'chhò-si'],
    ['答应', '答應', 'tah-ìng', 'tah-èng'],
    ['达到', '達到', 'ta̍t-kàu', 'ta̍t-kàu'],
    ['打工', '拍工', 'phah-kang', 'phah-kang', 'to work part time is 拍工'],
    ['打交道', '交陪', 'kau-puê', 'kau-pôe', 'to deal with someone is 交陪'],
    ['打喷嚏', '拍噴嚏', 'phah-phùn-thì', 'phah-phùn-thì', 'to sneeze is 拍噴嚏'],
    ['打听', '探聽', 'thàm-thiann', 'thàm-thiaⁿ', 'to ask about is 探聽'],
    ['大方', '大方', 'tāi-hong', 'tāi-hong'],
    ['大厦', '大廈', 'tāi-hā', 'tāi-hā'],
    ['大象', '大象', 'tāi-tshiūnn', 'tāi-chhiūⁿ'],
    ['大型', '大型', 'tāi-hîng', 'tāi-hêng'],
    ['呆', '呆', 'gōng', 'gōng', 'foolish is the colloquial reading gōng'],
    ['代表', '代表', 'tāi-piáu', 'tāi-piáu'],
    ['代替', '代替', 'tāi-thè', 'tāi-thè'],
    ['待遇', '待遇', 'tāi-gū', 'tāi-gū'],
    ['贷款', '貸款', 'tāi-khuán', 'tāi-khoán'],
    ['单纯', '單純', 'tan-sûn', 'tan-sûn'],
    ['单调', '單調', 'tan-tiāu', 'tan-tiāu'],
    ['单独', '單獨', 'tan-to̍k', 'tan-to̍k'],
    ['单位', '單位', 'tan-uī', 'tan-ūi'],
    ['单元', '單元', 'tan-guân', 'tan-goân'],
    ['担任', '擔任', 'tam-jīm', 'tam-jīm'],
    ['耽误', '耽誤', 'tam-gōo', 'tam-gō͘'],
    ['胆小鬼', '無膽鬼', 'bô-tánn-kuí', 'bô-táⁿ-kuí', 'a coward is 無膽鬼'],
    ['淡', '汫', 'tsiánn', 'chiáⁿ', 'bland is 汫'],
    ['当地', '當地', 'tong-tē', 'tong-tē'],
    ['当心', '當心', 'tòng-sim', 'tòng-sim'],
    ['挡', '擋', 'tòng', 'tòng'],
    ['倒霉', '衰', 'sue', 'soe', 'bad luck is 衰'],
    ['导演', '導演', 'tō-ián', 'tō-ián'],
    ['导致', '導致', 'tì-tō', 'tì-tō'],
    ['岛屿', '島嶼', 'tó-sū', 'tó-sū'],
    ['到达', '到達', 'kàu-ta̍t', 'kàu-ta̍t'],
    ['道德', '道德', 'tō-tik', 'tō-tek'],
    ['道理', '道理', 'tō-lí', 'tō-lí'],
    ['登记', '登記', 'ting-kì', 'teng-kì'],
    ['等待', '等待', 'tán-thāi', 'tán-thāi'],
    ['等于', '等於', 'tíng-î', 'téng-î'],
    ['滴', '滴', 'tih', 'tih'],
    ['敌人', '敵人', 'ti̍k-jîn', 'te̍k-jîn'],
    ['的确', '的確', 'tik-khak', 'tek-khak'],
    ['地道', '地道', 'tē-tō', 'tē-tō'],
    ['地理', '地理', 'tē-lí', 'tē-lí'],
    ['地区', '地區', 'tē-khu', 'tē-khu'],
    ['地毯', '地毯', 'tē-thán', 'tē-thán'],
    ['地位', '地位', 'tē-uī', 'tē-ūi'],
    ['地震', '地震', 'tē-tsín', 'tē-chín'],
    ['递', '遞', 'tē', 'tē'],
    ['点心', '點心', 'tiám-sim', 'tiám-sim'],
    ['电池', '電池', 'tiān-tî', 'tiān-tî'],
    ['电台', '電臺', 'tiān-tâi', 'tiān-tâi'],
    ['钓', '釣', 'tiò', 'tiò'],
    ['顶', '頂', 'tíng', 'téng'],
    ['冻', '凍', 'tàng', 'tàng', 'to freeze is the colloquial reading tàng'],
    ['动画片', '卡通', 'khah-thong', 'khah-thong', 'a cartoon is 卡通'],
    ['洞', '洞', 'tōng', 'tōng'],
    ['豆腐', '豆腐', 'tāu-hū', 'tāu-hū'],
    ['逗', '逗', 'tāu', 'tāu'],
    ['独立', '獨立', 'to̍k-li̍p', 'to̍k-li̍p'],
    ['独特', '獨特', 'to̍k-ti̍k', 'to̍k-te̍k'],
    ['度过', '度過', 'tōo-kuè', 'tō͘-kòe'],
    ['断', '斷', 'tn̄g', 'tn̄g'],
    ['堆', '堆', 'tui', 'tui'],
    ['兑换', '兌換', 'tuī-uānn', 'tūi-ōaⁿ'],
    ['对比', '對比', 'tuì-pí', 'tùi-pí'],
    ['对待', '對待', 'tuì-thāi', 'tùi-thāi'],
    ['对方', '對方', 'tuì-hong', 'tùi-hong'],
    ['对手', '對手', 'tuì-tshiú', 'tùi-chhiú'],
    ['对象', '對象', 'tuì-siōng', 'tùi-siōng'],
    ['吨', '噸', 'tùn', 'tùn'],
    ['蹲', '跍', 'khû', 'khû', 'to crouch is 跍'],
    ['顿', '頓', 'tùn', 'tùn'],
    ['多亏', '好佳哉', 'hó-ka-tsài', 'hó-ka-chài', 'thanks to is 好佳哉'],
    ['多余', '多餘', 'to-û', 'to-û'],
    ['朵', '蕊', 'luí', 'luí', 'the classifier for flowers is 蕊'],
    ['躲藏', '覕', 'bih', 'bih', 'to hide is 覕'],
    ['恶劣', '惡劣', 'ok-lua̍t', 'ok-loa̍t'],
    ['耳环', '耳鉤', 'hīnn-kau', 'hīⁿ-kau', 'an earring is 耳鉤'],
    ['发表', '發表', 'huat-piáu', 'hoat-piáu'],
    ['发愁', '發愁', 'huat-tshô', 'hoat-chhô', '煩惱 is taken by HSK 4 烦恼'],
    ['发达', '發達', 'huat-ta̍t', 'hoat-ta̍t'],
    ['发抖', '發抖', 'huat-táu', 'hoat-táu'],
    ['发挥', '發揮', 'huat-hui', 'hoat-hui'],
    ['发明', '發明', 'huat-bîng', 'hoat-bêng'],
    ['发票', '發票', 'huat-phiò', 'hoat-phiò'],
    ['发言', '發言', 'huat-giân', 'hoat-giân'],
    ['罚款', '罰款', 'hua̍t-khuán', 'hoa̍t-khoán'],
    ['法院', '法院', 'huat-īnn', 'hoat-īⁿ'],
    ['翻', '翻', 'huan', 'hoan'],
    ['繁荣', '繁榮', 'huân-îng', 'hoân-êng'],
    ['反而', '反而', 'huán-jî', 'hoán-jî'],
    ['反复', '反覆', 'huán-hok', 'hoán-hok'],
    ['反应', '反應', 'huán-ìng', 'hoán-èng'],
    ['反映', '反映', 'huán-ìng', 'hoán-èng'],
    ['反正', '反正', 'huán-tsìng', 'hoán-chèng'],
    ['范围', '範圍', 'huān-uî', 'hoān-ûi'],
    ['方', '方', 'hong', 'hong'],
    ['方案', '方案', 'hong-àn', 'hong-àn'],
    ['方式', '方式', 'hong-sik', 'hong-sek'],
    ['妨碍', '妨礙', 'hông-gāi', 'hông-gāi'],
    ['仿佛', '彷彿', 'hóng-hut', 'hóng-hut'],
    ['非', '非', 'hui', 'hui'],
    ['肥皂', '雪文', 'sap-bûn', 'sap-bûn', 'soap is 雪文'],
    ['废话', '廢話', 'huì-uē', 'huì-ōe'],
    ['分别', '分別', 'hun-pia̍t', 'hun-pia̍t'],
    ['分布', '分佈', 'hun-pòo', 'hun-pò͘'],
    ['分配', '分配', 'hun-phuè', 'hun-phòe'],
    ['分手', '分手', 'hun-tshiú', 'hun-chhiú'],
    ['分析', '分析', 'hun-sik', 'hun-sek'],
    ['纷纷', '紛紛', 'hun-hun', 'hun-hun'],
    ['奋斗', '奮鬥', 'hùn-tàu', 'hùn-tàu'],
    ['疯狂', '瘋狂', 'hong-kông', 'hong-kông'],
    ['风格', '風格', 'hong-kik', 'hong-kek'],
    ['风景', '風景', 'hong-kíng', 'hong-kéng'],
    ['风俗', '風俗', 'hong-sio̍k', 'hong-sio̍k'],
    ['风险', '風險', 'hong-hiám', 'hong-hiám'],
    ['讽刺', '諷刺', 'hóng-tshì', 'hóng-chhì'],
    ['否定', '否定', 'hóng-tīng', 'hóng-tēng'],
    ['否认', '否認', 'hóng-jīn', 'hóng-jīn'],
    ['幅', '幅', 'pak', 'pak'],
    ['扶', '扶', 'hû', 'hû'],
    ['服装', '服裝', 'ho̍k-tsong', 'ho̍k-chong'],
    ['辅导', '輔導', 'hú-tō', 'hú-tō'],
    ['复制', '複製', 'ho̍k-tsè', 'ho̍k-chè'],
    ['妇女', '婦女', 'hū-lú', 'hū-lú'],
    ['改革', '改革', 'kái-kik', 'kái-kek'],
    ['改进', '改進', 'kái-tsìn', 'kái-chìn'],
    ['改善', '改善', 'kái-siān', 'kái-siān'],
    ['改正', '改正', 'kái-tsìng', 'kái-chèng'],
]

export const HSK5_ROWS_B: readonly HandRow[] = [
    ['概括', '概括', 'khài-kuat', 'khài-koat'],
    ['概念', '概念', 'khài-liām', 'khài-liām'],
    ['盖', '蓋', 'kài', 'kài'],
    ['干脆', '乾脆', 'kan-tshuì', 'kan-chhùi'],
    ['干燥', '乾燥', 'kan-sò', 'kan-sò'],
    ['感激', '感激', 'kám-kik', 'kám-kek'],
    ['感受', '感受', 'kám-siū', 'kám-siū'],
    ['感想', '感想', 'kám-sióng', 'kám-sióng'],
    ['赶紧', '趕緊', 'kuánn-kín', 'kóaⁿ-kín'],
    ['赶快', '趕快', 'kuánn-khuài', 'kóaⁿ-khòai'],
    ['干活儿', '幹活', 'kàn-ua̍h', 'kàn-oa̍h'],
    ['钢铁', '鋼鐵', 'kǹg-thih', 'kǹg-thih'],
    ['高档', '高檔', 'ko-tóng', 'ko-tóng'],
    ['高级', '高級', 'ko-kip', 'ko-kip'],
    ['搞', '搞', 'kó', 'kó'],
    ['告别', '告別', 'kò-pia̍t', 'kò-pia̍t'],
    ['格外', '格外', 'kik-guā', 'kek-gōa'],
    ['隔壁', '隔壁', 'keh-piah', 'keh-piah'],
    ['个别', '個別', 'kò-pia̍t', 'kò-pia̍t'],
    ['个人', '個人', 'kò-jîn', 'kò-jîn'],
    ['个性', '個性', 'kò-sìng', 'kò-sèng'],
    ['各自', '各自', 'kok-tsū', 'kok-chū'],
    ['根', '根', 'kin', 'kin'],
    ['根本', '根本', 'kin-pún', 'kin-pún'],
    ['公布', '公佈', 'kong-pòo', 'kong-pò͘'],
    ['公开', '公開', 'kong-khai', 'kong-khai'],
    ['公平', '公平', 'kong-pîng', 'kong-pêng'],
    ['公寓', '公寓', 'kong-ū', 'kong-ū'],
    ['公元', '公元', 'kong-guân', 'kong-goân'],
    ['公主', '公主', 'kong-tsú', 'kong-chú'],
    ['功能', '功能', 'kong-lîng', 'kong-lêng'],
    ['工厂', '工廠', 'kang-tshiúnn', 'kang-chhiúⁿ'],
    ['工程师', '工程師', 'kang-tîng-su', 'kang-têng-su'],
    ['工具', '工具', 'kang-kū', 'kang-kū'],
    ['工人', '工人', 'kang-jîn', 'kang-jîn'],
    ['工业', '工業', 'kang-gia̍p', 'kang-gia̍p'],
    ['恭喜', '恭喜', 'kiong-hí', 'kiong-hí'],
    ['贡献', '貢獻', 'kòng-hiàn', 'kòng-hiàn'],
    ['沟通', '溝通', 'kau-thong', 'kau-thong'],
    ['构成', '構成', 'kòo-sîng', 'kò͘-sêng'],
    ['姑姑', '阿姑', 'a-koo', 'a-ko͘', 'a paternal aunt is 阿姑'],
    ['姑娘', '姑娘', 'koo-niû', 'ko͘-niû'],
    ['古代', '古代', 'kóo-tāi', 'kó͘-tāi'],
    ['古典', '古典', 'kóo-tián', 'kó͘-tián'],
    ['股票', '股票', 'kóo-phiò', 'kó͘-phiò'],
    ['骨头', '骨頭', 'kut-thâu', 'kut-thâu'],
    ['鼓舞', '鼓舞', 'kóo-bú', 'kó͘-bú'],
    ['鼓掌', '拍噗仔', 'phah-pho̍k-á', 'phah-pho̍k-á', 'to applaud is 拍噗仔'],
    ['固定', '固定', 'kòo-tīng', 'kò͘-tēng'],
    ['挂号', '掛號', 'kuà-hō', 'kòa-hō'],
    ['乖', '乖', 'kuai', 'koai'],
    ['拐弯', '轉彎', 'tńg-uan', 'tńg-oan', 'to turn a corner is 轉彎'],
    ['怪不得', '莫怪', 'bo̍k-kuài', 'bo̍k-koài', 'no wonder is 莫怪'],
    ['关闭', '關閉', 'kuan-pì', 'koan-pì'],
    ['官', '官', 'kuann', 'koaⁿ'],
    ['观察', '觀察', 'kuan-tshat', 'koan-chhat'],
    ['观点', '觀點', 'kuan-tiám', 'koan-tiám'],
    ['观念', '觀念', 'kuan-liām', 'koan-liām'],
    ['管子', '管仔', 'kóng-á', 'kóng-á'],
    ['冠军', '冠軍', 'kuàn-kun', 'kòan-kun'],
    ['光滑', '光滑', 'kong-ku̍t', 'kong-ku̍t'],
    ['光临', '光臨', 'kong-lîm', 'kong-lîm'],
    ['光明', '光明', 'kong-bîng', 'kong-bêng'],
    ['光盘', '光碟', 'kong-tia̍p', 'kong-tia̍p', 'a disc is 光碟 in Taiwan'],
    ['广场', '廣場', 'kóng-tiûnn', 'kóng-tiûⁿ'],
    ['广大', '廣大', 'kóng-tāi', 'kóng-tāi'],
    ['广泛', '廣泛', 'kóng-huàn', 'kóng-hoàn'],
    ['归纳', '歸納', 'kui-la̍p', 'kui-la̍p'],
    ['规矩', '規矩', 'kui-kí', 'kui-kí'],
    ['规律', '規律', 'kui-lu̍t', 'kui-lu̍t'],
    ['规模', '規模', 'kui-bôo', 'kui-bô͘'],
    ['规则', '規則', 'kui-tsik', 'kui-chek'],
    ['柜台', '櫃檯', 'kuī-tâi', 'kūi-tâi'],
    ['滚', '滾', 'kún', 'kún'],
    ['锅', '鍋', 'ue', 'oe', 'a pot is the colloquial reading ue'],
    ['国庆节', '國慶節', 'kok-khìng-tsiat', 'kok-khèng-chiat'],
    ['国王', '國王', 'kok-ông', 'kok-ông'],
    ['果然', '果然', 'kó-jiân', 'kó-jiân'],
    ['果实', '果實', 'kó-si̍t', 'kó-si̍t'],
    ['过分', '過分', 'kuè-hūn', 'kòe-hūn'],
    ['过敏', '過敏', 'kuè-bín', 'kòe-bín'],
    ['过期', '過期', 'kuè-kî', 'kòe-kî'],
    ['哈', '哈', 'hah', 'hah'],
    ['海关', '海關', 'hái-kuan', 'hái-koan'],
    ['海鲜', '海鮮', 'hái-sian', 'hái-sian'],
    ['喊', '喊', 'hiàm', 'hiàm'],
    ['行业', '行業', 'hâng-gia̍p', 'hâng-gia̍p'],
    ['豪华', '豪華', 'hô-huâ', 'hô-hoâ'],
    ['好客', '好客', 'hònn-kheh', 'hòⁿ-kheh'],
    ['好奇', '好奇', 'hònn-kî', 'hòⁿ-kî'],
    ['何必', '何必', 'hô-pit', 'hô-pit'],
    ['何况', '何況', 'hô-hóng', 'hô-hóng'],
    ['合法', '合法', 'ha̍p-huat', 'ha̍p-hoat'],
    ['合理', '合理', 'ha̍p-lí', 'ha̍p-lí'],
    ['合同', '合同', 'ha̍p-tông', 'ha̍p-tông'],
    ['合影', '合影', 'ha̍p-iánn', 'ha̍p-iáⁿ'],
    ['合作', '合作', 'ha̍p-tsok', 'ha̍p-chok'],
    ['和平', '和平', 'hô-pîng', 'hô-pêng'],
    ['核心', '核心', 'hi̍k-sim', 'he̍k-sim'],
    ['恨', '恨', 'hūn', 'hūn'],
    ['猴子', '猴仔', 'kâu-á', 'kâu-á'],
    ['后背', '後壁', 'āu-piah', 'āu-piah', 'the back is 後壁'],
    ['后果', '後果', 'hōo-kó', 'hō͘-kó'],
    ['呼吸', '呼吸', 'hoo-khip', 'ho͘-khip'],
    ['忽然', '忽然', 'hut-jiân', 'hut-jiân'],
    ['忽视', '忽視', 'hut-sī', 'hut-sī'],
    ['壶', '壺', 'ôo', 'ô͘'],
    ['糊涂', '糊塗', 'hôo-tôo', 'hô͘-tô͘'],
    ['胡说', '亂講', 'luān-kóng', 'loān-kóng', 'to talk nonsense is 亂講'],
    ['胡同', '巷仔', 'hāng-á', 'hāng-á', 'a lane is 巷仔'],
    ['蝴蝶', '蝴蝶', 'ôo-tia̍p', 'ô͘-tia̍p'],
    ['花生', '土豆', 'thôo-tāu', 'thô͘-tāu', 'a peanut is 土豆'],
    ['华裔', '華裔', 'huâ-è', 'hoâ-è'],
    ['滑', '滑', 'ku̍t', 'ku̍t'],
    ['划', '划', 'kò', 'kò', 'to row is the colloquial reading kò'],
    ['化学', '化學', 'huà-ha̍k', 'hòa-ha̍k'],
    ['话题', '話題', 'uē-tê', 'ōe-tê'],
    ['怀念', '懷念', 'huâi-liām', 'hoâi-liām'],
    ['怀孕', '有身', 'ū-sin', 'ū-sin', 'to be pregnant is 有身'],
    ['缓解', '緩解', 'huān-kái', 'hoān-kái'],
    ['幻想', '幻想', 'huàn-sióng', 'hoàn-sióng'],
    ['慌张', '慌張', 'hong-tiunn', 'hong-tiuⁿ'],
    ['黄金', '黃金', 'n̂g-kim', 'n̂g-kim', 'gold uses the colloquial reading of 黃'],
    ['恢复', '恢復', 'hue-ho̍k', 'hoe-ho̍k'],
    ['挥', '揮', 'hui', 'hui'],
    ['灰', '灰', 'hue', 'hoe'],
    ['灰尘', '灰塵', 'hue-tîn', 'hoe-tîn'],
    ['灰心', '灰心', 'hue-sim', 'hoe-sim'],
    ['汇率', '匯率', 'huē-lu̍t', 'hōe-lu̍t'],
    ['婚礼', '婚禮', 'hun-lé', 'hun-lé'],
    ['婚姻', '婚姻', 'hun-in', 'hun-in'],
    ['活跃', '活躍', 'hua̍t-io̍k', 'hoa̍t-io̍k'],
    ['伙伴', '伙伴', 'hué-phuānn', 'hóe-phōaⁿ'],
    ['火柴', '番仔火', 'huan-á-hué', 'hoan-á-hóe', 'a match is 番仔火'],
    ['或许', '或許', 'hi̍k-hí', 'he̍k-hí'],
    ['基本', '基本', 'ki-pún', 'ki-pún'],
    ['机器', '機器', 'ki-khì', 'ki-khì'],
    ['激烈', '激烈', 'kik-lia̍t', 'kek-lia̍t'],
    ['肌肉', '肌肉', 'ki-bah', 'ki-bah', 'meat is 肉 bah'],
    ['及格', '及格', 'ki̍p-kik', 'ki̍p-kek'],
    ['急忙', '急忙', 'kip-bâng', 'kip-bâng'],
    ['急诊', '急診', 'kip-tsín', 'kip-chín'],
    ['极其', '極其', 'ki̍k-kî', 'ke̍k-kî'],
    ['集合', '集合', 'tsi̍p-ha̍p', 'chi̍p-ha̍p'],
    ['集体', '集體', 'tsi̍p-thé', 'chi̍p-thé'],
    ['集中', '集中', 'tsi̍p-tiong', 'chi̍p-tiong'],
    ['寂寞', '寂寞', 'tsi̍k-bo̍k', 'che̍k-bo̍k'],
    ['系领带', '縛領帶', 'pa̍k-niá-tuà', 'pa̍k-niá-tòa', 'to tie is 縛'],
    ['纪录', '紀錄', 'kì-lo̍k', 'kì-lo̍k'],
    ['纪律', '紀律', 'kì-lu̍t', 'kì-lu̍t'],
    ['纪念', '紀念', 'kì-liām', 'kì-liām'],
    ['计算', '計算', 'kè-sǹg', 'kè-sǹg'],
    ['记录', '記錄', 'kì-lo̍k', 'kì-lo̍k'],
    ['记忆', '記憶', 'kì-ik', 'kì-ek'],
    ['嘉宾', '嘉賓', 'ka-pin', 'ka-pin'],
    ['夹子', '夾仔', 'giap-á', 'giap-á'],
    ['家庭', '家庭', 'ka-tîng', 'ka-têng'],
    ['家务', '家事', 'ka-sū', 'ka-sū', 'housework is 家事'],
    ['家乡', '家鄉', 'ka-hiong', 'ka-hiong'],
    ['假如', '假如', 'ká-jû', 'ká-jû'],
    ['假设', '假設', 'ká-siat', 'ká-siat'],
    ['假装', '假裝', 'ké-tsong', 'ké-chong'],
    ['甲', '甲', 'kah', 'kah'],
    ['价值', '價值', 'kè-ta̍t', 'kè-ta̍t'],
    ['嫁', '嫁', 'kè', 'kè', 'of a woman, to marry is the colloquial reading kè'],
    ['驾驶', '駕駛', 'kà-sú', 'kà-sú'],
    ['兼职', '兼職', 'kiam-tsit', 'kiam-chit'],
    ['坚决', '堅決', 'kian-kuat', 'kian-koat'],
    ['坚强', '堅強', 'kian-kiông', 'kian-kiông'],
    ['肩膀', '肩胛頭', 'king-kah-thâu', 'keng-kah-thâu', 'the shoulder is 肩胛頭'],
    ['艰巨', '艱鉅', 'kan-kū', 'kan-kū'],
    ['艰苦', '艱苦', 'kan-khóo', 'kan-khó͘'],
    ['剪刀', '鉸刀', 'ka-to', 'ka-to', 'scissors are 鉸刀'],
    ['捡', '抾', 'khioh', 'khioh', 'to pick up is 抾'],
    ['简历', '簡歷', 'kán-li̍k', 'kán-le̍k'],
    ['简直', '簡直', 'kán-ti̍t', 'kán-ti̍t'],
    ['健身', '健身', 'kiān-sin', 'kiān-sin'],
    ['建立', '建立', 'kiàn-li̍p', 'kiàn-li̍p'],
    ['建设', '建設', 'kiàn-siat', 'kiàn-siat'],
    ['建筑', '建築', 'kiàn-tio̍k', 'kiàn-tio̍k'],
    ['键盘', '鍵盤', 'kiān-puânn', 'kiān-pôaⁿ'],
    ['讲究', '講究', 'káng-kiù', 'káng-kiù'],
    ['讲座', '講座', 'káng-tsō', 'káng-chō'],
    ['酱油', '豆油', 'tāu-iû', 'tāu-iû', 'soy sauce is 豆油'],
    ['交换', '交換', 'kau-uānn', 'kau-ōaⁿ'],
    ['交际', '交際', 'kau-tsè', 'kau-chè'],
    ['交往', '交往', 'kau-óng', 'kau-óng'],
    ['浇', '淋', 'lâm', 'lâm', 'to pour on is 淋'],
    ['胶水', '膠水', 'kau-tsuí', 'kau-chúi'],
    ['狡猾', '狡猾', 'káu-kua̍t', 'káu-koa̍t'],
    ['角度', '角度', 'kak-tōo', 'kak-tō͘'],
    ['教材', '教材', 'kàu-tsâi', 'kàu-châi'],
    ['教练', '教練', 'kàu-liān', 'kàu-liān'],
    ['教训', '教訓', 'kàu-hùn', 'kàu-hùn'],
    ['接触', '接觸', 'tsiap-tshiok', 'chiap-chhiok'],
    ['接待', '接待', 'tsiap-thāi', 'chiap-thāi'],
    ['接近', '接近', 'tsiap-kīn', 'chiap-kīn'],
    ['结实', '結實', 'kiat-si̍t', 'kiat-si̍t'],
    ['阶段', '階段', 'kai-tuānn', 'kai-tōaⁿ'],
    ['结构', '結構', 'kiat-kòo', 'kiat-kò͘'],
    ['结合', '結合', 'kiat-ha̍p', 'kiat-ha̍p'],
    ['结论', '結論', 'kiat-lūn', 'kiat-lūn'],
    ['结账', '算數', 'sǹg-siàu', 'sǹg-siàu', 'to pay the bill is 算數'],
    ['节省', '節省', 'tsiat-síng', 'chiat-séng'],
    ['借口', '藉口', 'tsioh-kháu', 'chioh-kháu'],
    ['届', '屆', 'kài', 'kài'],
    ['戒', '戒', 'kài', 'kài'],
    ['戒指', '手指', 'tshiú-tsí', 'chhiú-chí', 'a finger ring is 手指'],
    ['金属', '金屬', 'kim-sio̍k', 'kim-sio̍k'],
    ['尽快', '儘快', 'tsín-khuài', 'chín-khòai'],
    ['紧急', '緊急', 'kín-kip', 'kín-kip'],
    ['谨慎', '謹慎', 'kín-sīn', 'kín-sīn'],
    ['尽力', '盡力', 'tsīn-li̍k', 'chīn-le̍k'],
    ['尽量', '儘量', 'tsín-liōng', 'chín-liōng'],
    ['近代', '近代', 'kīn-tāi', 'kīn-tāi'],
    ['进步', '進步', 'tsìn-pōo', 'chìn-pō͘'],
    ['进口', '進口', 'tsìn-kháu', 'chìn-kháu'],
    ['精力', '精力', 'tsing-li̍k', 'cheng-le̍k'],
    ['精神', '精神', 'tsing-sîn', 'cheng-sîn'],
    ['经典', '經典', 'king-tián', 'keng-tián'],
    ['经商', '經商', 'king-siong', 'keng-siong'],
    ['经营', '經營', 'king-îng', 'keng-êng'],
    ['酒吧', '酒吧', 'tsiú-pa', 'chiú-pa'],
    ['救', '救', 'kiù', 'kiù'],
    ['救护车', '救護車', 'kiù-hōo-tshia', 'kiù-hō͘-chhia'],
    ['舅舅', '阿舅', 'a-kū', 'a-kū', 'a maternal uncle is 阿舅'],
    ['居然', '居然', 'ki-jiân', 'ki-jiân'],
    ['桔子', '柑仔', 'kam-á', 'kam-á', 'a tangerine is 柑仔'],
    ['俱乐部', '俱樂部', 'kū-lo̍k-pōo', 'kū-lo̍k-pō͘'],
    ['具备', '具備', 'kū-pī', 'kū-pī'],
    ['具体', '具體', 'kū-thé', 'kū-thé'],
    ['巨大', '巨大', 'kū-tāi', 'kū-tāi'],
    ['据说', '據說', 'kì-suat', 'kì-soat'],
    ['捐', '捐', 'kuan', 'koan'],
    ['决赛', '決賽', 'kuat-sài', 'koat-sài'],
    ['决心', '決心', 'kuat-sim', 'koat-sim'],
    ['绝对', '絕對', 'tsua̍t-tuì', 'choa̍t-tùi'],
    ['角色', '角色', 'kak-sik', 'kak-sek'],
    ['军事', '軍事', 'kun-sū', 'kun-sū'],
    ['均匀', '均勻', 'kun-ûn', 'kun-ûn'],
    ['卡车', '卡車', 'khah-tshia', 'khah-chhia'],
    ['开发', '開發', 'khai-huat', 'khai-hoat'],
    ['开放', '開放', 'khai-hòng', 'khai-hòng'],
    ['开幕式', '開幕式', 'khai-mōo-sik', 'khai-mō͘-sek'],
    ['开水', '滾水', 'kún-tsuí', 'kún-chúi', 'boiled water is 滾水'],
    ['砍', '砍', 'khám', 'khám'],
    ['看不起', '看無起', 'khuànn-bô-khí', 'khòaⁿ-bô-khí', 'to look down on is 看無起'],
    ['看望', '探訪', 'thàm-hóng', 'thàm-hóng', 'to visit is 探訪'],
    ['靠', '靠', 'khò', 'khò'],
    ['颗', '粒', 'lia̍p', 'lia̍p', 'the classifier for small round things is 粒'],
    ['可见', '可見', 'khó-kiàn', 'khó-kiàn'],
    ['可靠', '可靠', 'khó-khò', 'khó-khò'],
    ['可怕', '可怕', 'khó-phànn', 'khó-phàⁿ'],
    ['克', '克', 'khik', 'khek'],
    ['克服', '克服', 'khik-ho̍k', 'khek-ho̍k'],
    ['刻苦', '刻苦', 'khik-khóo', 'khek-khó͘'],
    ['客观', '客觀', 'khik-kuan', 'khek-koan'],
    ['课程', '課程', 'khò-tîng', 'khò-têng'],
    ['空间', '空間', 'khong-kan', 'khong-kan'],
    ['控制', '控制', 'khòng-tsè', 'khòng-chè'],
    ['空闲', '空閒', 'khàng-îng', 'khàng-êng'],
    ['口味', '口味', 'kháu-bī', 'kháu-bī'],
    ['夸', '誇', 'khua', 'khoa'],
    ['夸张', '誇張', 'khua-tiunn', 'khoa-tiuⁿ'],
    ['会计', '會計', 'kuè-kè', 'kòe-kè'],
    ['宽', '寬', 'khuann', 'khoaⁿ'],
    ['昆虫', '昆蟲', 'khun-thiông', 'khun-thiông'],
    ['扩大', '擴大', 'khok-tāi', 'khok-tāi'],
    ['辣椒', '辣椒', 'hiam-tsio', 'hiam-chio'],
    ['拦', '攔', 'nuâ', 'nôa'],
    ['烂', '爛', 'nuā', 'nōa'],
    ['朗读', '朗讀', 'lóng-tho̍k', 'lóng-tho̍k'],
    ['劳动', '勞動', 'lô-tōng', 'lô-tōng'],
    ['劳驾', '勞駕', 'lô-kà', 'lô-kà'],
    ['姥姥', '外媽', 'guā-má', 'gōa-má', "a mother's mother is 外媽"],
    ['老百姓', '老百姓', 'lāu-peh-sènn', 'lāu-peh-sèⁿ'],
    ['老板', '頭家', 'thâu-ke', 'thâu-ke', 'a boss is 頭家'],
    ['老婆', '牽手', 'khan-tshiú', 'khan-chhiú', 'a spouse is 牽手; 某 is taken by 妻子'],
    ['老实', '老實', 'láu-si̍t', 'láu-si̍t'],
    ['老鼠', '鳥鼠', 'niáu-tshí', 'niáu-chhí', 'a rat is 鳥鼠'],
    ['乐观', '樂觀', 'lo̍k-kuan', 'lo̍k-koan'],
    ['雷', '雷', 'luî', 'luî'],
    ['类型', '類型', 'luī-hîng', 'luī-hêng'],
    ['冷淡', '冷淡', 'líng-tām', 'léng-tām'],
    ['厘米', '釐米', 'lî-bí', 'lî-bí'],
    ['梨', '梨', 'lâi', 'lâi'],
    ['离婚', '離婚', 'lī-hun', 'lī-hun'],
    ['理论', '理論', 'lí-lūn', 'lí-lūn'],
    ['理由', '理由', 'lí-iû', 'lí-iû'],
    ['利润', '利潤', 'lī-jūn', 'lī-jūn'],
    ['利息', '利息', 'lī-sik', 'lī-sek'],
    ['利益', '利益', 'lī-ik', 'lī-ek'],
    ['利用', '利用', 'lī-iōng', 'lī-iōng'],
    ['力量', '力量', 'li̍k-liōng', 'le̍k-liōng'],
    ['立即', '立即', 'li̍p-tsik', 'li̍p-chek'],
    ['立刻', '立刻', 'li̍p-khik', 'li̍p-khek'],
    ['联合', '聯合', 'liân-ha̍p', 'liân-ha̍p'],
    ['连忙', '連忙', 'liân-bâng', 'liân-bâng'],
    ['连续', '連續', 'liân-sio̍k', 'liân-sio̍k'],
    ['恋爱', '戀愛', 'luân-ài', 'loân-ài'],
]

export const HSK5_ROWS_C: readonly HandRow[] = [
    ['粮食', '糧食', 'liông-si̍t', 'liông-si̍t'],
    ['良好', '良好', 'liông-hó', 'liông-hó'],
    ['亮', '亮', 'liāng', 'liāng'],
    ['了不起', '了不起', 'liáu-put-khí', 'liáu-put-khí'],
    ['列车', '列車', 'lia̍t-tshia', 'lia̍t-chhia'],
    ['临时', '臨時', 'lîm-sî', 'lîm-sî'],
    ['灵活', '靈活', 'lîng-hua̍t', 'lêng-hoa̍t'],
    ['铃', '鈴', 'lîng', 'lêng'],
    ['零件', '零件', 'lîng-kiānn', 'lêng-kiāⁿ'],
    ['零食', '零食', 'lîng-si̍t', 'lêng-si̍t'],
    ['领导', '領導', 'líng-tō', 'léng-tō'],
    ['领域', '領域', 'líng-hi̍k', 'léng-he̍k'],
    ['流传', '流傳', 'liû-thuân', 'liû-thoân'],
    ['流泪', '流目屎', 'lâu-ba̍k-sái', 'lâu-ba̍k-sái', 'to shed tears is 流目屎'],
    ['浏览', '瀏覽', 'liû-lám', 'liû-lám'],
    ['龙', '龍', 'lîng', 'lêng'],
    ['漏', '漏', 'lāu', 'lāu'],
    ['录取', '錄取', 'lo̍k-tshú', 'lo̍k-chhú'],
    ['录音', '錄音', 'lo̍k-im', 'lo̍k-im'],
    ['陆地', '陸地', 'lio̍k-tē', 'lio̍k-tē'],
    ['陆续', '陸續', 'lio̍k-sio̍k', 'lio̍k-sio̍k'],
    ['轮流', '輪流', 'lûn-liû', 'lûn-liû'],
    ['论文', '論文', 'lūn-bûn', 'lūn-bûn'],
    ['逻辑', '邏輯', 'lô-tsi̍p', 'lô-chi̍p'],
    ['落后', '落後', 'lo̍h-āu', 'lo̍h-āu'],
    ['骂', '罵', 'mē', 'mē'],
    ['麦克风', '麥克風', 'be̍h-khik-hong', 'be̍h-khek-hong'],
    ['馒头', '饅頭', 'bán-thâu', 'bán-thâu'],
    ['满足', '滿足', 'muá-tsiok', 'móa-chiok'],
    ['毛病', '毛病', 'môo-pēnn', 'mô͘-pēⁿ'],
    ['矛盾', '矛盾', 'mâu-tún', 'mâu-tún'],
    ['冒险', '冒險', 'mōo-hiám', 'mō͘-hiám'],
    ['贸易', '貿易', 'bōo-i̍k', 'bō͘-e̍k'],
    ['媒体', '媒體', 'muî-thé', 'mûi-thé'],
    ['煤炭', '煤炭', 'muî-thuànn', 'mûi-thòaⁿ'],
    ['眉毛', '目眉', 'ba̍k-bâi', 'ba̍k-bâi', 'an eyebrow is 目眉'],
    ['美术', '美術', 'bí-su̍t', 'bí-su̍t'],
    ['魅力', '魅力', 'bī-li̍k', 'bī-le̍k'],
    ['梦想', '夢想', 'bōng-sióng', 'bōng-sióng'],
    ['密切', '密切', 'bi̍t-tshiat', 'bi̍t-chhiat'],
    ['秘密', '秘密', 'pì-bi̍t', 'pì-bi̍t'],
    ['秘书', '秘書', 'pì-su', 'pì-su'],
    ['蜜蜂', '蜜蜂', 'bi̍t-phang', 'bi̍t-phang'],
    ['面对', '面對', 'bīn-tuì', 'bīn-tùi'],
    ['面积', '面積', 'bīn-tsik', 'bīn-chek'],
    ['面临', '面臨', 'bīn-lîm', 'bīn-lîm'],
    ['描写', '描寫', 'biâu-siá', 'biâu-siá'],
    ['苗条', '苗條', 'biâu-tiâu', 'biâu-tiâu'],
    ['敏感', '敏感', 'bín-kám', 'bín-kám'],
    ['名牌', '名牌', 'miâ-pâi', 'miâ-pâi'],
    ['名片', '名片', 'miâ-phìnn', 'miâ-phìⁿ'],
    ['名胜古迹', '名勝古蹟', 'bîng-sìng-kóo-tsik', 'bêng-sèng-kó͘-chek'],
    ['明确', '明確', 'bîng-khak', 'bêng-khak'],
    ['明显', '明顯', 'bîng-hiánn', 'bêng-hiáⁿ'],
    ['明星', '明星', 'bîng-sing', 'bêng-seng'],
    ['命令', '命令', 'bīng-līng', 'bēng-lēng'],
    ['命运', '命運', 'bīng-ūn', 'bēng-ūn'],
    ['摸', '摸', 'mo', 'mo'],
    ['摩托车', '摩托車', 'môo-thok-tshia', 'mô͘-thok-chhia'],
    ['模仿', '模仿', 'bôo-hóng', 'bô͘-hóng'],
    ['模糊', '模糊', 'bôo-hôo', 'bô͘-hô͘'],
    ['模特', '模特', 'bôo-ti̍k', 'bô͘-te̍k'],
    ['陌生', '生份', 'tshenn-hūn', 'chheⁿ-hūn', 'to be unfamiliar is 生份'],
    ['某', '某', 'bóo', 'bó͘'],
    ['木头', '柴頭', 'tshâ-thâu', 'chhâ-thâu', 'a blockhead is 柴頭'],
    ['目标', '目標', 'bo̍k-piau', 'bo̍k-piau'],
    ['目录', '目錄', 'bo̍k-lo̍k', 'bo̍k-lo̍k'],
    ['目前', '目前', 'bo̍k-tsiân', 'bo̍k-chiân'],
    ['哪怕', '哪怕', 'ná-phànn', 'ná-phàⁿ'],
    ['难怪', '難怪', 'lân-kuài', 'lân-koài'],
    ['难免', '難免', 'lân-bián', 'lân-bián'],
    ['脑袋', '頭殼', 'thâu-khak', 'thâu-khak', 'the head as a body part is 頭殼'],
    ['内部', '內部', 'lāi-pōo', 'lāi-pō͘'],
    ['内科', '內科', 'lāi-kho', 'lāi-kho'],
    ['嫩', '嫩', 'lūn', 'lūn'],
    ['能干', '能幹', 'lîng-kàn', 'lêng-kàn'],
    ['能源', '能源', 'lîng-guân', 'lêng-goân'],
    ['嗯', '嗯', 'hng', 'hng'],
    ['年代', '年代', 'nî-tāi', 'nî-tāi'],
    ['年纪', '年紀', 'nî-kí', 'nî-kí'],
    ['念', '數念', 'siàu-liām', 'siàu-liām', 'to miss someone is 數念'],
    ['宁可', '寧可', 'lîng-khó', 'lêng-khó'],
    ['牛仔裤', '牛仔褲', 'gû-á-khòo', 'gû-á-khò͘'],
    ['农村', '農村', 'lông-tshun', 'lông-chhun'],
    ['农民', '農民', 'lông-bîn', 'lông-bîn'],
    ['农业', '農業', 'lông-gia̍p', 'lông-gia̍p'],
    ['浓', '濃', 'lông', 'lông'],
    ['女士', '女士', 'lú-sū', 'lú-sū'],
    ['欧洲', '歐洲', 'au-tsiu', 'au-chiu'],
    ['偶然', '偶然', 'ngóo-jiân', 'ngó͘-jiân'],
    ['拍', '翕相', 'hip-siòng', 'hip-siòng', 'to take a photo is 翕相'],
    ['派', '派', 'phài', 'phài'],
    ['盼望', '盼望', 'phàn-bōng', 'phàn-bōng'],
    ['培训', '培訓', 'puê-hùn', 'pôe-hùn'],
    ['培养', '培養', 'puê-ióng', 'pôe-ióng'],
    ['赔偿', '賠償', 'puê-siông', 'pôe-siông'],
    ['佩服', '佩服', 'pē-ho̍k', 'pē-ho̍k'],
    ['配合', '配合', 'phuè-ha̍p', 'phòe-ha̍p'],
    ['盆', '盆', 'phûn', 'phûn'],
    ['碰', '碰', 'phōng', 'phōng'],
    ['批', '批', 'phue', 'phoe'],
    ['批准', '批准', 'phue-tsún', 'phoe-chún'],
    ['披', '披', 'phi', 'phi'],
    ['疲劳', '疲勞', 'phî-lô', 'phî-lô'],
    ['匹', '匹', 'phit', 'phit'],
    ['片', '片', 'phìnn', 'phìⁿ'],
    ['片面', '片面', 'phiàn-bīn', 'phiàn-bīn'],
    ['飘', '飄', 'phiau', 'phiau'],
    ['拼音', '拼音', 'phing-im', 'pheng-im'],
    ['频道', '頻道', 'pîn-tō', 'pîn-tō'],
    ['凭', '憑', 'pîn', 'pîn'],
    ['平均', '平均', 'pîng-kun', 'pêng-kun'],
    ['平', '平', 'pîng', 'pêng'],
    ['平安', '平安', 'pîng-an', 'pêng-an'],
    ['平常', '平常', 'pîng-siông', 'pêng-siông'],
    ['平等', '平等', 'pîng-tíng', 'pêng-téng'],
    ['平方', '平方', 'pîng-hong', 'pêng-hong'],
    ['平衡', '平衡', 'pîng-hîng', 'pêng-hêng'],
    ['平静', '平靜', 'pîng-tsīng', 'pêng-chēng'],
    ['评价', '評價', 'phîng-kè', 'phêng-kè'],
    ['破产', '破產', 'phò-sán', 'phò-sán'],
    ['破坏', '破壞', 'phò-huāi', 'phò-hoāi'],
    ['迫切', '迫切', 'phik-tshiat', 'phek-chhiat'],
    ['期待', '期待', 'kî-thāi', 'kî-thāi'],
    ['期间', '期間', 'kî-kan', 'kî-kan'],
    ['其余', '其餘', 'kî-û', 'kî-û'],
    ['奇迹', '奇蹟', 'kî-tsik', 'kî-chek'],
    ['企业', '企業', 'khì-gia̍p', 'khì-gia̍p'],
    ['启发', '啟發', 'khé-huat', 'khé-hoat'],
    ['气氛', '氣氛', 'khì-hun', 'khì-hun'],
    ['汽油', '汽油', 'khì-iû', 'khì-iû'],
    ['签', '籤', 'tshiam', 'chhiam'],
    ['谦虚', '謙虛', 'khiam-hu', 'khiam-hu'],
    ['前途', '前途', 'tsiân-tôo', 'chiân-tô͘'],
    ['浅', '淺', 'tshián', 'chhián'],
    ['欠', '欠', 'khiàm', 'khiàm'],
    ['枪', '槍', 'tshiunn', 'chhiuⁿ'],
    ['墙', '牆', 'tshiûnn', 'chhiûⁿ'],
    ['强调', '強調', 'kiông-tiāu', 'kiông-tiāu'],
    ['强烈', '強烈', 'kiông-lia̍t', 'kiông-lia̍t'],
    ['抢', '搶', 'tshiúnn', 'chhiúⁿ'],
    ['悄悄', '悄悄', 'tshiau-tshiau', 'chhiau-chhiau'],
    ['瞧', '看', 'khuànn', 'khòaⁿ', 'to look at is the everyday verb 看'],
    ['巧妙', '巧妙', 'khá-miāu', 'khá-miāu'],
    ['切', '切', 'tshiat', 'chhiat'],
    ['亲爱', '親愛', 'tshin-ài', 'chhin-ài'],
    ['亲切', '親切', 'tshin-tshiat', 'chhin-chhiat'],
    ['亲自', '親自', 'tshin-tsū', 'chhin-chū'],
    ['勤奋', '勤奮', 'khîn-hùn', 'khîn-hùn'],
    ['清淡', '清淡', 'tshing-tām', 'chheng-tām'],
    ['轻视', '輕視', 'khing-sī', 'kheng-sī'],
    ['轻易', '輕易', 'khing-ī', 'kheng-ī'],
    ['青', '青', 'tshenn', 'chheⁿ'],
    ['青春', '青春', 'tshing-tshun', 'chheng-chhun'],
    ['青少年', '青少年', 'tshing-siàu-liân', 'chheng-siàu-liân'],
    ['情景', '情景', 'tsîng-kíng', 'chêng-kéng'],
    ['情绪', '情緒', 'tsîng-sū', 'chêng-sū'],
    ['请求', '請求', 'tshíng-kiû', 'chhéng-kiû'],
    ['庆祝', '慶祝', 'khìng-tsok', 'khèng-chok'],
    ['球迷', '球迷', 'kiû-bê', 'kiû-bê'],
    ['趋势', '趨勢', 'tshu-sè', 'chhu-sè'],
    ['取消', '取消', 'tshú-siau', 'chhú-siau'],
    ['娶', '娶', 'tshuā', 'chhōa'],
    ['去世', '過身', 'kuè-sin', 'kòe-sin', 'to pass away is 過身'],
    ['圈', '圈', 'khuan', 'khoan'],
    ['全面', '全面', 'tsuân-bīn', 'choân-bīn'],
    ['权利', '權利', 'kuân-lī', 'koân-lī'],
    ['权力', '權力', 'kuân-li̍k', 'koân-le̍k'],
    ['劝', '勸', 'khǹg', 'khǹg'],
    ['缺乏', '缺乏', 'khuat-hua̍t', 'khoat-hoa̍t'],
    ['确定', '確定', 'khak-tīng', 'khak-tēng'],
    ['确认', '確認', 'khak-jīn', 'khak-jīn'],
    ['群', '群', 'kûn', 'kûn'],
    ['燃烧', '燃燒', 'jiân-sio', 'jiân-sio'],
    ['绕', '踅', 'se̍h', 'se̍h', 'to go round is 踅'],
    ['热爱', '熱愛', 'jia̍t-ài', 'jia̍t-ài'],
    ['热烈', '熱烈', 'jia̍t-lia̍t', 'jia̍t-lia̍t'],
    ['热心', '熱心', 'jia̍t-sim', 'jia̍t-sim'],
    ['人才', '人才', 'jîn-tsâi', 'jîn-châi'],
    ['人口', '人口', 'jîn-kháu', 'jîn-kháu'],
    ['人类', '人類', 'jîn-luī', 'jîn-lūi'],
    ['人民币', '人民幣', 'jîn-bîn-pè', 'jîn-bîn-pè'],
    ['人生', '人生', 'jîn-sing', 'jîn-seng'],
    ['人事', '人事', 'jîn-sū', 'jîn-sū'],
    ['人物', '人物', 'jîn-bu̍t', 'jîn-bu̍t'],
    ['人员', '人員', 'jîn-guân', 'jîn-goân'],
    ['忍不住', '忍不住', 'jím-put-tsū', 'jím-put-chū'],
    ['日常', '日常', 'ji̍t-siông', 'ji̍t-siông'],
    ['日程', '日程', 'ji̍t-tîng', 'ji̍t-têng'],
    ['日历', '日曆', 'ji̍t-li̍k', 'ji̍t-le̍k'],
    ['日期', '日期', 'ji̍t-kî', 'ji̍t-kî'],
    ['日用品', '日用品', 'ji̍t-iōng-phín', 'ji̍t-iōng-phín'],
    ['日子', '日子', 'ji̍t-tsí', 'ji̍t-chí'],
    ['如何', '如何', 'jû-hô', 'jû-hô'],
    ['如今', '如今', 'jû-kim', 'jû-kim'],
    ['软', '軟', 'nńg', 'nńg', 'soft is the colloquial reading nńg'],
    ['软件', '軟件', 'nńg-kiānn', 'nńg-kiāⁿ'],
    ['弱', '弱', 'jio̍k', 'jio̍k'],
    ['洒', '潑', 'phuah', 'phoah', 'to sprinkle is 潑'],
    ['嗓子', '喉嚨', 'âu-lêng', 'âu-lêng', 'the throat is 喉嚨'],
    ['色彩', '色彩', 'sik-tshái', 'sek-chhái'],
    ['杀', '殺', 'sat', 'sat'],
    ['沙漠', '沙漠', 'sa-bo̍k', 'sa-bo̍k'],
    ['沙滩', '沙灘', 'sua-thuann', 'soa-thoaⁿ'],
    ['傻', '戇', 'gōng', 'gōng', 'foolish is 戇'],
    ['晒', '曝', 'pha̍k', 'pha̍k', 'to dry in the sun is 曝'],
    ['删除', '刪除', 'san-tû', 'san-tû'],
    ['闪电', '閃電', 'siám-tiān', 'siám-tiān'],
    ['善良', '善良', 'siān-liông', 'siān-liông'],
    ['善于', '善於', 'siān-û', 'siān-û'],
    ['扇子', '扇仔', 'sìnn-á', 'sìⁿ-á'],
    ['伤害', '傷害', 'siong-hāi', 'siong-hāi'],
    ['商品', '商品', 'siong-phín', 'siong-phín'],
    ['商务', '商務', 'siong-bū', 'siong-bū'],
    ['商业', '商業', 'siong-gia̍p', 'siong-gia̍p'],
    ['上当', '受騙', 'siū-phiàn', 'siū-phiàn', 'to be taken in is 受騙'],
    ['蛇', '蛇', 'tsuâ', 'chôa'],
    ['舍不得', '捨不得', 'siá-put-ti̍k', 'siá-put-te̍k'],
    ['射击', '射擊', 'siā-kik', 'siā-kek'],
    ['摄影', '攝影', 'liap-iánn', 'liap-iáⁿ'],
    ['设备', '設備', 'siat-pī', 'siat-pī'],
    ['设计', '設計', 'siat-kè', 'siat-kè'],
    ['设施', '設施', 'siat-si', 'siat-si'],
    ['伸', '伸', 'tshun', 'chhun'],
    ['深刻', '深刻', 'tshim-khik', 'chhim-khek'],
    ['身材', '身材', 'sin-tsâi', 'sin-châi'],
    ['身份', '身份', 'sin-hūn', 'sin-hūn'],
    ['神话', '神話', 'sîn-uē', 'sîn-ōe'],
    ['神秘', '神秘', 'sîn-pì', 'sîn-pì'],
    ['升', '升', 'sing', 'seng'],
    ['声调', '聲調', 'siann-tiāu', 'siaⁿ-tiāu'],
    ['生产', '生產', 'sing-sán', 'seng-sán'],
    ['生动', '生動', 'sing-tōng', 'seng-tōng'],
    ['生长', '生長', 'sing-tióng', 'seng-tióng'],
    ['绳子', '索仔', 'soh-á', 'soh-á', 'a rope is 索仔'],
    ['省略', '省略', 'síng-lio̍k', 'séng-lio̍k'],
    ['胜利', '勝利', 'sìng-lī', 'sèng-lī'],
    ['失眠', '失眠', 'sit-bîn', 'sit-bîn'],
    ['失去', '失去', 'sit-khì', 'sit-khì'],
    ['失业', '失業', 'sit-gia̍p', 'sit-gia̍p'],
    ['湿润', '溼潤', 'sip-jūn', 'sip-jūn'],
    ['狮子', '獅仔', 'sai-á', 'sai-á'],
    ['诗', '詩', 'si', 'si'],
    ['实话', '實話', 'si̍t-uē', 'si̍t-ōe'],
    ['实践', '實踐', 'si̍t-tsiān', 'si̍t-chiān'],
    ['实习', '實習', 'si̍t-si̍p', 'si̍t-si̍p'],
    ['实现', '實現', 'si̍t-hiān', 'si̍t-hiān'],
    ['实验', '實驗', 'si̍t-giām', 'si̍t-giām'],
    ['实用', '實用', 'si̍t-iōng', 'si̍t-iōng'],
    ['时差', '時差', 'sî-tsha', 'sî-chha'],
    ['时代', '時代', 'sî-tāi', 'sî-tāi'],
    ['时刻', '時刻', 'sî-khik', 'sî-khek'],
    ['时髦', '時髦', 'sî-môo', 'sî-mô͘'],
    ['时期', '時期', 'sî-kî', 'sî-kî'],
    ['时尚', '時尚', 'sî-siōng', 'sî-siōng'],
    ['石头', '石頭', 'tsio̍h-thâu', 'chio̍h-thâu'],
    ['食物', '食物', 'si̍t-bu̍t', 'si̍t-bu̍t'],
    ['使劲儿', '使勁', 'sái-kìng', 'sái-kèng'],
    ['始终', '始終', 'sí-tsiong', 'sí-chiong'],
    ['事实', '事實', 'sū-si̍t', 'sū-si̍t'],
    ['事物', '事物', 'sū-bu̍t', 'sū-bu̍t'],
    ['事先', '事先', 'sū-sian', 'sū-sian'],
    ['似的', '親像', 'tshin-tshiūnn', 'chhin-chhiūⁿ', 'seems as if is 親像'],
    ['士兵', '士兵', 'sū-ping', 'sū-peng'],
    ['市场', '市場', 'tshī-tiûnn', 'chhī-tiûⁿ'],
    ['试卷', '試卷', 'tshì-kuàn', 'chhì-koàn'],
    ['收获', '收穫', 'siu-hi̍k', 'siu-he̍k'],
    ['收据', '收據', 'siu-kì', 'siu-kì'],
    ['手工', '手工', 'tshiú-kang', 'chhiú-kang'],
    ['手术', '手術', 'tshiú-su̍t', 'chhiú-su̍t'],
    ['手套', '手套', 'tshiú-thò', 'chhiú-thò'],
    ['手续', '手續', 'tshiú-sio̍k', 'chhiú-sio̍k'],
    ['手指', '手指頭', 'tshiú-tsí-thâu', 'chhiú-chí-thâu', 'a finger is 手指頭; 手指 alone is the ring'],
    ['首', '首', 'siú', 'siú'],
    ['受伤', '受傷', 'siū-siong', 'siū-siong'],
    ['寿命', '壽命', 'siū-bīng', 'siū-bēng'],
    ['书架', '冊架仔', 'tsheh-kè-á', 'chheh-kè-á', 'a bookshelf is 冊架仔'],
    ['梳子', '梳仔', 'sue-á', 'soe-á'],
    ['舒适', '舒適', 'su-sik', 'su-sek'],
    ['蔬菜', '蔬菜', 'soo-tshài', 'so͘-chhài'],
    ['输入', '輸入', 'su-ji̍p', 'su-ji̍p'],
    ['熟练', '熟練', 'si̍k-liān', 'se̍k-liān'],
    ['属于', '屬於', 'sio̍k-û', 'sio̍k-û'],
    ['数', '數', 'sòo', 'sò͘'],
    ['鼠标', '滑鼠', 'ku̍t-tshú', 'ku̍t-chhú', 'a computer mouse is 滑鼠 in Taiwan'],
    ['数据', '數據', 'sòo-kì', 'sò͘-kì'],
    ['数码', '數碼', 'sòo-bé', 'sò͘-bé'],
    ['摔倒', '跋倒', 'pua̍h-tó', 'poa̍h-tó', 'to fall over is 跋倒'],
    ['甩', '甩', 'siak', 'siak', 'the verb is siak, as for 摔'],
    ['双方', '雙方', 'siong-hong', 'siong-hong'],
    ['税', '稅', 'suè', 'sòe'],
    ['说不定', '說不定', 'suat-put-tīng', 'soat-put-tēng'],
    ['说服', '說服', 'suat-ho̍k', 'soat-ho̍k'],
    ['丝绸', '絲綢', 'si-tiû', 'si-tiû'],
    ['丝毫', '絲毫', 'si-hô', 'si-hô'],
    ['思考', '思考', 'su-khó', 'su-khó'],
    ['思想', '思想', 'su-sióng', 'su-sióng'],
    ['撕', '撕', 'si', 'si'],
    ['私人', '私人', 'su-jîn', 'su-jîn'],
    ['似乎', '似乎', 'sū-hôo', 'sū-hô͘'],
]

export const HSK5_ROWS_D: readonly HandRow[] = [
    ['搜索', '搜尋', 'sau-sîn', 'sau-sîn', 'to search for is 搜尋'],
    ['宿舍', '宿舍', 'sok-sià', 'sok-sià'],
    ['随身', '隨身', 'suî-sin', 'sûi-sin'],
    ['随时', '隨時', 'suî-sî', 'sûi-sî'],
    ['随手', '隨手', 'suî-tshiú', 'sûi-chhiú'],
    ['碎', '碎', 'tshuì', 'chhuì'],
    ['损失', '損失', 'sún-sit', 'sún-sit'],
    ['缩短', '縮短', 'sok-té', 'sok-té'],
    ['所', '所', 'sóo', 'só͘'],
    ['锁', '鎖', 'só', 'só'],
    ['台阶', '臺階', 'tâi-kai', 'tâi-kai'],
    ['太极拳', '太極拳', 'thài-ki̍k-kûn', 'thài-ke̍k-kûn'],
    ['太太', '太太', 'thài-thài', 'thài-thài'],
    ['谈判', '談判', 'tâm-phuànn', 'tâm-phòaⁿ'],
    ['坦率', '坦率', 'thán-sut', 'thán-sut'],
    ['烫', '燙', 'thǹg', 'thǹg'],
    ['桃', '桃', 'thô', 'thô'],
    ['淘气', '淘氣', 'tô-khì', 'tô-khì'],
    ['逃', '逃', 'tô', 'tô'],
    ['逃避', '逃避', 'tô-pī', 'tô-pī'],
    ['讨价还价', '討價還價', 'thó-kè-huân-kè', 'thó-kè-hoân-kè'],
    ['套', '套', 'thò', 'thò'],
    ['特色', '特色', 'ti̍k-sik', 'te̍k-sek'],
    ['特殊', '特殊', 'ti̍k-sû', 'te̍k-sû'],
    ['特征', '特徵', 'ti̍k-ting', 'te̍k-teng'],
    ['疼爱', '疼愛', 'thiànn-ài', 'thiàⁿ-ài'],
    ['提倡', '提倡', 'thê-tshiòng', 'thê-chhiòng'],
    ['提纲', '提綱', 'thê-kang', 'thê-kang'],
    ['提问', '提問', 'thê-būn', 'thê-būn'],
    ['题目', '題目', 'tê-bo̍k', 'tê-bo̍k'],
    ['体会', '體會', 'thé-huē', 'thé-hōe'],
    ['体贴', '體貼', 'thé-thiap', 'thé-thiap'],
    ['体现', '體現', 'thé-hiān', 'thé-hiān'],
    ['体验', '體驗', 'thé-giām', 'thé-giām'],
    ['天空', '天空', 'thian-khong', 'thian-khong'],
    ['天真', '天真', 'thian-tsin', 'thian-chin'],
    ['调皮', '調皮', 'thiâu-phî', 'thiâu-phî'],
    ['调整', '調整', 'tiâu-tsíng', 'tiâu-chéng'],
    ['挑战', '挑戰', 'thiau-tsiàn', 'thiau-chiàn'],
    ['通常', '通常', 'thong-siông', 'thong-siông'],
    ['统一', '統一', 'thóng-it', 'thóng-it'],
    ['痛苦', '痛苦', 'thòng-khóo', 'thòng-khó͘'],
    ['痛快', '痛快', 'thòng-khuài', 'thòng-khòai'],
    ['偷', '偷', 'thau', 'thau'],
    ['投入', '投入', 'tâu-ji̍p', 'tâu-ji̍p'],
    ['投资', '投資', 'tâu-tsu', 'tâu-chu'],
    ['透明', '透明', 'thàu-bîng', 'thàu-bêng'],
    ['突出', '突出', 'tu̍t-tshut', 'tu̍t-chhut'],
    ['土地', '土地', 'thóo-tē', 'thó͘-tē'],
    ['土豆', '馬鈴薯', 'má-lîng-tsî', 'má-lêng-chî', 'a potato is 馬鈴薯; 土豆 means peanut in Taiwan'],
    ['兔子', '兔仔', 'thòo-á', 'thò͘-á'],
    ['吐', '吐', 'thòo', 'thò͘'],
    ['团', '團', 'thuân', 'thoân'],
    ['推辞', '推辭', 'the-tshî', 'the-chhî'],
    ['推广', '推廣', 'the-kóng', 'the-kóng'],
    ['推荐', '推薦', 'the-tshian', 'the-chhian'],
    ['退', '退', 'thè', 'thè'],
    ['退步', '退步', 'thè-pōo', 'thè-pō͘'],
    ['退休', '退休', 'thè-hiu', 'thè-hiu'],
    ['歪', '歪', 'uai', 'oai'],
    ['外公', '外公', 'guā-kong', 'gōa-kong'],
    ['外交', '外交', 'guā-kau', 'gōa-kau'],
    ['完美', '完美', 'uân-bí', 'oân-bí'],
    ['完善', '完善', 'uân-siān', 'oân-siān'],
    ['完整', '完整', 'uân-tsíng', 'oân-chéng'],
    ['玩具', '玩具', 'uân-kū', 'oân-kū'],
    ['万一', '萬一', 'bān-it', 'bān-it'],
    ['王子', '王子', 'ông-tsú', 'ông-chú'],
    ['往返', '往返', 'óng-huán', 'óng-hoán'],
    ['网络', '網路', 'bāng-lōo', 'bāng-lō͘', 'the Internet is 網路 in Taiwan'],
    ['危害', '危害', 'guî-hāi', 'gûi-hāi'],
    ['威胁', '威脅', 'ui-hia̍p', 'ui-hia̍p'],
    ['微笑', '微笑', 'bî-tshiò', 'bî-chhiò'],
    ['唯一', '唯一', 'uî-it', 'ûi-it'],
    ['围巾', '圍巾', 'uî-kin', 'ûi-kin'],
    ['围绕', '圍繞', 'uî-jiàu', 'ûi-jiàu'],
    ['维修', '維修', 'uî-siu', 'ûi-siu'],
    ['违反', '違反', 'uî-huán', 'ûi-hoán'],
    ['伟大', '偉大', 'uí-tāi', 'úi-tāi'],
    ['委屈', '委屈', 'uí-khut', 'úi-khut'],
    ['尾巴', '尾仔', 'bué-á', 'bóe-á'],
    ['位于', '位於', 'uī-û', 'ūi-û'],
    ['位置', '位置', 'uī-tì', 'ūi-tì'],
    ['未必', '未必', 'bī-pit', 'bī-pit'],
    ['未来', '未來', 'bī-lâi', 'bī-lâi'],
    ['胃', '胃', 'uī', 'ūi'],
    ['胃口', '胃口', 'uī-kháu', 'ūi-kháu'],
    ['温暖', '溫暖', 'un-luán', 'un-lóan'],
    ['温柔', '溫柔', 'un-jiû', 'un-jiû'],
    ['文件', '文件', 'bûn-kiānn', 'bûn-kiāⁿ'],
    ['文具', '文具', 'bûn-kū', 'bûn-kū'],
    ['文明', '文明', 'bûn-bîng', 'bûn-bêng'],
    ['文学', '文學', 'bûn-ha̍k', 'bûn-ha̍k'],
    ['文字', '文字', 'bûn-jī', 'bûn-jī'],
    ['闻', '聞', 'bûn', 'bûn'],
    ['吻', '唚', 'tsim', 'chim', 'to kiss is 唚'],
    ['稳定', '穩定', 'ún-tīng', 'ún-tēng'],
    ['问候', '問候', 'būn-hāu', 'būn-hāu'],
    ['卧室', '睏房', 'khùn-pâng', 'khùn-pâng', 'a bedroom is 睏房'],
    ['握手', '握手', 'ak-tshiú', 'ak-chhiú'],
    ['屋子', '厝', 'tshù', 'chhù', 'a house is 厝'],
    ['无奈', '無奈', 'bô-nāi', 'bô-nāi'],
    ['无数', '無數', 'bô-sòo', 'bô-sò͘'],
    ['无所谓', '無所謂', 'bô-sóo-uī', 'bô-só͘-ūi'],
    ['武术', '武術', 'bú-su̍t', 'bú-su̍t'],
    ['勿', '莫', 'mài', 'mài', 'do not is 莫 mài'],
    ['物理', '物理', 'bu̍t-lí', 'bu̍t-lí'],
    ['物质', '物質', 'bu̍t-tsit', 'bu̍t-chit'],
    ['雾', '霧', 'bū', 'bū'],
    ['吸取', '吸取', 'khip-tshú', 'khip-chhú'],
    ['吸收', '吸收', 'khip-siu', 'khip-siu'],
    ['戏剧', '戲劇', 'hì-kio̍k', 'hì-kio̍k'],
    ['系', '系', 'hē', 'hē'],
    ['系统', '系統', 'hē-thóng', 'hē-thóng'],
    ['细节', '細節', 'sè-tsiat', 'sè-chiat'],
    ['瞎', '青盲', 'tshenn-mê', 'chheⁿ-mê', 'blind is 青盲'],
    ['下载', '下載', 'hā-tsài', 'hā-chài'],
    ['吓', '嚇', 'heh', 'heh'],
    ['夏令营', '夏令營', 'hā-līng-iânn', 'hā-lēng-iâⁿ'],
    ['鲜艳', '鮮豔', 'sian-iām', 'sian-iām'],
    ['显得', '顯得', 'hián-ti̍k', 'hián-te̍k'],
    ['显然', '顯然', 'hián-jiân', 'hián-jiân'],
    ['显示', '顯示', 'hián-sī', 'hián-sī'],
    ['县', '縣', 'kuān', 'koān'],
    ['现代', '現代', 'hiān-tāi', 'hiān-tāi'],
    ['现实', '現實', 'hiān-si̍t', 'hiān-si̍t'],
    ['现象', '現象', 'hiān-siōng', 'hiān-siōng'],
    ['限制', '限制', 'hān-tsè', 'hān-chè'],
    ['相处', '相處', 'siong-tshú', 'siong-chhú'],
    ['相当', '相當', 'siong-tong', 'siong-tong'],
    ['相对', '相對', 'siong-tuì', 'siong-tùi'],
    ['相关', '相關', 'siong-kuan', 'siong-koan'],
    ['相似', '相似', 'siong-sū', 'siong-sū'],
    ['香肠', '煙腸', 'ian-tshiâng', 'ian-chhiâng', 'a sausage is 煙腸'],
    ['享受', '享受', 'hiáng-siū', 'hiáng-siū'],
    ['想念', '想念', 'sióng-liām', 'sióng-liām'],
    ['想象', '想像', 'sióng-siōng', 'sióng-siōng'],
    ['象棋', '象棋', 'siōng-kî', 'siōng-kî'],
    ['象征', '象徵', 'siōng-ting', 'siōng-teng'],
    ['项', '項', 'hāng', 'hāng'],
    ['项链', '項鍊', 'hāng-liān', 'hāng-liān'],
    ['项目', '項目', 'hāng-bo̍k', 'hāng-bo̍k'],
    ['消费', '消費', 'siau-huì', 'siau-hùi'],
    ['消化', '消化', 'siau-huà', 'siau-hòa'],
    ['消极', '消極', 'siau-ki̍k', 'siau-ke̍k'],
    ['消失', '消失', 'siau-sit', 'siau-sit'],
    ['销售', '銷售', 'siau-siū', 'siau-siū'],
    ['小麦', '小麥', 'sió-be̍h', 'sió-be̍h'],
    ['小气', '小氣', 'sió-khì', 'sió-khì'],
    ['孝顺', '孝順', 'hàu-sūn', 'hàu-sūn'],
    ['效率', '效率', 'hāu-lu̍t', 'hāu-lu̍t'],
    ['歇', '歇', 'hioh', 'hioh'],
    ['斜', '斜', 'tshiâ', 'chhiâ'],
    ['写作', '寫作', 'siá-tsok', 'siá-chok'],
    ['心理', '心理', 'sim-lí', 'sim-lí'],
    ['心脏', '心臟', 'sim-tsōng', 'sim-chōng'],
    ['欣赏', '欣賞', 'him-sióng', 'him-sióng'],
    ['信号', '信號', 'sìn-hō', 'sìn-hō'],
    ['信任', '信任', 'sìn-jīm', 'sìn-jīm'],
    ['形成', '形成', 'hîng-sîng', 'hêng-sêng'],
    ['形容', '形容', 'hîng-iông', 'hêng-iông'],
    ['形势', '形勢', 'hîng-sè', 'hêng-sè'],
    ['形式', '形式', 'hîng-sik', 'hêng-sek'],
    ['形象', '形象', 'hîng-siōng', 'hêng-siōng'],
    ['形状', '形狀', 'hîng-tsōng', 'hêng-chōng'],
    ['行动', '行動', 'hîng-tōng', 'hêng-tōng'],
    ['行人', '行人', 'hîng-jîn', 'hêng-jîn'],
    ['行为', '行為', 'hîng-uî', 'hêng-ûi'],
    ['幸亏', '幸虧', 'hīng-khui', 'hēng-khui'],
    ['幸运', '幸運', 'hīng-ūn', 'hēng-ūn'],
    ['性质', '性質', 'sìng-tsit', 'sèng-chit'],
    ['兄弟', '兄弟', 'hiann-tī', 'hiaⁿ-tī'],
    ['胸', '胸坎', 'hing-khám', 'heng-khám', 'the chest is 胸坎'],
    ['休闲', '休閒', 'hiu-hân', 'hiu-hân'],
    ['修改', '修改', 'siu-kái', 'siu-kái'],
    ['虚心', '虛心', 'hi-sim', 'hi-sim'],
    ['叙述', '敘述', 'sū-su̍t', 'sū-su̍t'],
    ['宣布', '宣佈', 'suan-pòo', 'soan-pò͘'],
    ['宣传', '宣傳', 'suan-thuân', 'soan-thoân'],
    ['学历', '學歷', 'ha̍k-li̍k', 'ha̍k-le̍k'],
    ['学术', '學術', 'ha̍k-su̍t', 'ha̍k-su̍t'],
    ['学问', '學問', 'ha̍k-būn', 'ha̍k-būn'],
    ['血', '血', 'hueh', 'hoeh'],
    ['寻找', '尋找', 'tsîm-tshuē', 'chîm-chhōe'],
    ['询问', '詢問', 'sûn-būn', 'sûn-būn'],
    ['训练', '訓練', 'hùn-liān', 'hùn-liān'],
    ['迅速', '迅速', 'sìn-sok', 'sìn-sok'],
    ['押金', '押金', 'ah-kim', 'ah-kim'],
    ['牙齿', '牙齒', 'gê-khí', 'gê-khí'],
    ['严肃', '嚴肅', 'giâm-siok', 'giâm-siok'],
    ['延长', '延長', 'iân-tn̂g', 'iân-tn̂g'],
    ['演讲', '演講', 'ián-káng', 'ián-káng'],
    ['宴会', '宴會', 'iàn-huē', 'iàn-hōe'],
    ['阳台', '陽臺', 'iûnn-tâi', 'iûⁿ-tâi'],
    ['痒', '癢', 'tsiūnn', 'chiūⁿ'],
    ['样式', '樣式', 'iūnn-sik', 'iūⁿ-sek'],
    ['腰', '腰', 'io', 'io'],
    ['摇', '搖', 'iô', 'iô'],
    ['咬', '咬', 'kā', 'kā'],
    ['要不', '抑無', 'ia̍h-bô', 'ia̍h-bô', 'otherwise is 抑無; 若無 is taken by 不然'],
    ['业务', '業務', 'gia̍p-bū', 'gia̍p-bū'],
    ['业余', '業餘', 'gia̍p-û', 'gia̍p-û'],
    ['夜', '夜', 'iā', 'iā'],
    ['依然', '依然', 'i-jiân', 'i-jiân'],
    ['一辈子', '一輩子', 'tsi̍t-puè-tsí', 'chi̍t-pòe-chí'],
    ['一旦', '一旦', 'it-tàn', 'it-tàn'],
    ['一律', '一律', 'it-lu̍t', 'it-lu̍t'],
    ['一再', '一再', 'it-tsài', 'it-chài'],
    ['一致', '一致', 'it-tì', 'it-tì'],
    ['疑问', '疑問', 'gî-būn', 'gî-būn'],
    ['移动', '移動', 'î-tōng', 'î-tōng'],
    ['移民', '移民', 'î-bîn', 'î-bîn'],
    ['遗憾', '遺憾', 'uî-hām', 'ûi-hām'],
    ['乙', '乙', 'it', 'it'],
    ['以及', '以及', 'í-ki̍p', 'í-ki̍p'],
    ['以来', '以來', 'í-lâi', 'í-lâi'],
    ['义务', '義務', 'gī-bū', 'gī-bū'],
    ['亿', '億', 'ik', 'ek'],
    ['意外', '意外', 'ì-guā', 'ì-gōa'],
    ['意义', '意義', 'ì-gī', 'ì-gī'],
    ['议论', '議論', 'gī-lūn', 'gī-lūn'],
    ['因而', '因而', 'in-jî', 'in-jî'],
    ['因素', '因素', 'in-sòo', 'in-sò͘'],
    ['银', '銀', 'gîn', 'gîn'],
    ['印刷', '印刷', 'ìn-suat', 'ìn-soat'],
    ['英俊', '英俊', 'ing-tsùn', 'eng-chùn'],
    ['英雄', '英雄', 'ing-hiông', 'eng-hiông'],
    ['营养', '營養', 'îng-ióng', 'êng-ióng'],
    ['营业', '營業', 'îng-gia̍p', 'êng-gia̍p'],
    ['迎接', '迎接', 'gîng-tsiap', 'gêng-chiap'],
    ['影子', '影子', 'iánn-á', 'iáⁿ-á'],
    ['应付', '應付', 'ìng-hù', 'èng-hù'],
    ['应用', '應用', 'ìng-iōng', 'èng-iōng'],
    ['硬', '硬', 'ngē', 'ngē'],
    ['硬件', '硬件', 'ngē-kiānn', 'ngē-kiāⁿ'],
    ['拥抱', '擁抱', 'ióng-phō', 'ióng-phō'],
    ['拥挤', '擁擠', 'ióng-tsè', 'ióng-chè'],
    ['勇气', '勇氣', 'ióng-khì', 'ióng-khì'],
    ['用功', '用功', 'iōng-kong', 'iōng-kong'],
    ['用途', '用途', 'iōng-tôo', 'iōng-tô͘'],
    ['优惠', '優惠', 'iu-huī', 'iu-hūi'],
    ['优美', '優美', 'iu-bí', 'iu-bí'],
    ['优势', '優勢', 'iu-sè', 'iu-sè'],
    ['悠久', '悠久', 'iu-kiú', 'iu-kiú'],
    ['油炸', '油炸', 'iû-tsà', 'iû-chà'],
    ['游览', '遊覽', 'iû-lám', 'iû-lám'],
    ['犹豫', '躊躇', 'tiû-tû', 'tiû-tû', 'to hesitate is 躊躇'],
    ['有利', '有利', 'iú-lī', 'iú-lī'],
    ['幼儿园', '幼兒園', 'iù-jî-hn̂g', 'iù-jî-hn̂g'],
    ['娱乐', '娛樂', 'gôo-lo̍k', 'gô͘-lo̍k'],
    ['与其', '與其', 'í-kî', 'í-kî'],
    ['语气', '語氣', 'gí-khì', 'gí-khì'],
    ['玉米', '番麥', 'huan-be̍h', 'hoan-be̍h', 'corn is 番麥'],
    ['预报', '預報', 'ī-pò', 'ī-pò'],
    ['预订', '預訂', 'ī-tīng', 'ī-tēng'],
    ['预防', '預防', 'ī-hông', 'ī-hông'],
    ['元旦', '元旦', 'guân-tàn', 'goân-tàn'],
    ['原料', '原料', 'guân-liāu', 'goân-liāu'],
    ['原则', '原則', 'guân-tsik', 'goân-chek'],
    ['员工', '員工', 'guân-kang', 'goân-kang'],
    ['圆', '圓', 'înn', 'îⁿ'],
    ['愿望', '願望', 'guān-bōng', 'goān-bōng'],
    ['乐器', '樂器', 'ga̍k-khì', 'ga̍k-khì'],
    ['晕', '暈', 'hūn', 'hūn'],
    ['运气', '運氣', 'ūn-khì', 'ūn-khì'],
    ['运输', '運輸', 'ūn-su', 'ūn-su'],
    ['运用', '運用', 'ūn-iōng', 'ūn-iōng'],
    ['灾害', '災害', 'tsai-hāi', 'chai-hāi'],
    ['再三', '再三', 'tsài-sann', 'chài-saⁿ'],
    ['在乎', '在乎', 'tsāi-hôo', 'chāi-hô͘'],
    ['在于', '在於', 'tsāi-û', 'chāi-û'],
    ['赞成', '贊成', 'tsàn-sîng', 'chàn-sêng'],
    ['赞美', '讚美', 'tsàn-bí', 'chàn-bí'],
    ['糟糕', '糟糕', 'tsau-ko', 'chau-ko'],
    ['造成', '造成', 'tsō-sîng', 'chō-sêng'],
    ['则', '則', 'tsik', 'chek'],
    ['责备', '責備', 'tsik-pī', 'chek-pī'],
    ['摘', '摘', 'tiah', 'tiah'],
    ['窄', '狹', 'e̍h', 'e̍h', 'narrow is 狹'],
    ['粘贴', '粘貼', 'liâm-thiap', 'liâm-thiap'],
    ['展开', '展開', 'thián-khui', 'thián-khui'],
    ['展览', '展覽', 'tián-lám', 'tián-lám'],
    ['占', '佔', 'tsiàm', 'chiàm'],
    ['战争', '戰爭', 'tsiàn-tsing', 'chiàn-cheng'],
    ['掌握', '掌握', 'tsióng-ak', 'chióng-ak'],
    ['涨', '漲', 'tiòng', 'tiòng'],
    ['长辈', '長輩', 'tióng-puè', 'tióng-pòe'],
    ['账户', '戶頭', 'hōo-thâu', 'hō͘-thâu', 'a bank account is 戶頭'],
    ['招待', '招待', 'tsiau-thāi', 'chiau-thāi'],
    ['着火', '著火', 'to̍h-hué', 'to̍h-hóe'],
    ['着凉', '著涼', 'tio̍h-liâng', 'tio̍h-liâng'],
    ['召开', '召開', 'tiàu-khui', 'tiàu-khui'],
    ['照常', '照常', 'tsiàu-siông', 'chiàu-siông'],
    ['哲学', '哲學', 'tiat-ha̍k', 'tiat-ha̍k'],
    ['珍惜', '珍惜', 'tin-sioh', 'tin-sioh', '惜 has the colloquial reading sioh'],
    ['真实', '真實', 'tsin-si̍t', 'chin-si̍t'],
    ['针对', '針對', 'tsiam-tuì', 'chiam-tùi'],
    ['诊断', '診斷', 'tsín-tuàn', 'chín-toàn'],
    ['振动', '振動', 'tsín-tōng', 'chín-tōng'],
    ['阵', '陣', 'tsūn', 'chūn'],
]

export const HSK5_ROWS_E: readonly HandRow[] = [
    ['争论', '爭論', 'tsing-lūn', 'cheng-lūn'],
    ['争取', '爭取', 'tsing-tshú', 'cheng-chhú'],
    ['征求', '徵求', 'tsing-kiû', 'cheng-kiû'],
    ['挣', '掙', 'tsing', 'cheng'],
    ['睁', '睜', 'tsing', 'cheng'],
    ['整个', '整個', 'tsíng-kò', 'chéng-kò'],
    ['整齐', '整齊', 'tsíng-tsê', 'chéng-chê'],
    ['整体', '整體', 'tsíng-thé', 'chéng-thé'],
    ['政府', '政府', 'tsìng-hú', 'chèng-hú'],
    ['政治', '政治', 'tsìng-tī', 'chèng-tī'],
    ['正', '正', 'tsiànn', 'chiàⁿ', 'right or correct is the colloquial reading tsiànn'],
    ['证件', '證件', 'tsìng-kiānn', 'chèng-kiāⁿ'],
    ['证据', '證據', 'tsìng-kì', 'chèng-kì'],
    ['支', '支', 'ki', 'ki'],
    ['支票', '支票', 'tsi-phiò', 'chi-phiò'],
    ['执照', '執照', 'tsip-tsiàu', 'chip-chiàu'],
    ['直', '直', 'ti̍t', 'ti̍t'],
    ['指导', '指導', 'tsí-tō', 'chí-tō'],
    ['指挥', '指揮', 'tsí-hui', 'chí-hui'],
    ['制定', '制定', 'tsè-tīng', 'chè-tēng'],
    ['制度', '制度', 'tsè-tōo', 'chè-tō͘'],
    ['制造', '製造', 'tsè-tsō', 'chè-chō'],
    ['制作', '製作', 'tsè-tsok', 'chè-chok'],
    ['志愿者', '志願者', 'tsì-guān-tsiá', 'chì-goān-chiá'],
    ['智慧', '智慧', 'tì-huī', 'tì-hūi'],
    ['治疗', '治療', 'tī-liâu', 'tī-liâu'],
    ['秩序', '秩序', 'tia̍t-sū', 'tia̍t-sū'],
    ['至今', '至今', 'tsì-kim', 'chì-kim'],
    ['至于', '至於', 'tsì-û', 'chì-û'],
    ['中介', '中介', 'tiong-kài', 'tiong-kài'],
    ['中心', '中心', 'tiong-sim', 'tiong-sim'],
    ['中旬', '中旬', 'tiong-sûn', 'tiong-sûn'],
    ['种类', '種類', 'tsíng-luī', 'chéng-lūi'],
    ['重大', '重大', 'tiōng-tāi', 'tiōng-tāi'],
    ['重量', '重量', 'tiōng-liōng', 'tiōng-liōng'],
    ['周到', '周到', 'tsiu-tò', 'chiu-tò'],
    ['猪', '豬', 'ti', 'ti'],
    ['竹子', '竹仔', 'tik-á', 'tek-á'],
    ['逐步', '逐步', 'ti̍k-pōo', 'te̍k-pō͘'],
    ['逐渐', '逐漸', 'ti̍k-tsiām', 'te̍k-chiām'],
    ['主持', '主持', 'tsú-tshî', 'chú-chhî'],
    ['主动', '主動', 'tsú-tōng', 'chú-tōng'],
    ['主观', '主觀', 'tsú-kuan', 'chú-koan'],
    ['主人', '主人', 'tsú-lâng', 'chú-lâng', 'a host or owner is 主人 with the colloquial reading of 人'],
    ['主任', '主任', 'tsú-jīm', 'chú-jīm'],
    ['主题', '主題', 'tsú-tê', 'chú-tê'],
    ['主席', '主席', 'tsú-si̍k', 'chú-se̍k'],
    ['主张', '主張', 'tsú-tiunn', 'chú-tiuⁿ'],
    ['煮', '煮', 'tsú', 'chú'],
    ['注册', '註冊', 'tsù-tsheh', 'chù-chheh'],
    ['祝福', '祝福', 'tsiok-hok', 'chiok-hok'],
    ['抓', '掠', 'lia̍h', 'lia̍h', 'to grab is 掠'],
    ['抓紧', '掠牢', 'lia̍h-tiâu', 'lia̍h-tiâu', 'to grasp firmly is 掠牢'],
    ['专家', '專家', 'tsuan-ka', 'choan-ka'],
    ['专心', '專心', 'tsuan-sim', 'choan-sim'],
    ['转变', '轉變', 'tsuán-piàn', 'chóan-piàn'],
    ['转告', '轉告', 'tsuán-kò', 'chóan-kò'],
    ['装', '裝', 'tsng', 'chng'],
    ['装饰', '裝飾', 'tsng-sik', 'chng-sek'],
    ['装修', '裝修', 'tsng-siu', 'chng-siu'],
    ['撞', '撞', 'tōng', 'tōng'],
    ['状况', '狀況', 'tsōng-hóng', 'chōng-hóng'],
    ['状态', '狀態', 'tsōng-thài', 'chōng-thài'],
    ['追', '追', 'tui', 'tui'],
    ['追求', '追求', 'tui-kiû', 'tui-kiû'],
    ['咨询', '諮詢', 'tsu-sûn', 'chu-sûn'],
    ['姿势', '姿勢', 'tsu-sè', 'chu-sè'],
    ['资格', '資格', 'tsu-kik', 'chu-kek'],
    ['资金', '資金', 'tsu-kim', 'chu-kim'],
    ['资料', '資料', 'tsu-liāu', 'chu-liāu'],
    ['资源', '資源', 'tsu-guân', 'chu-goân'],
    ['紫', '紫', 'tsí', 'chí'],
    ['字母', '字母', 'jī-bó', 'jī-bó'],
    ['字幕', '字幕', 'jī-bō', 'jī-bō'],
    ['自从', '自從', 'tsū-tsiông', 'chū-chiông'],
    ['自动', '自動', 'tsū-tōng', 'chū-tōng'],
    ['自豪', '自豪', 'tsū-hô', 'chū-hô'],
    ['自觉', '自覺', 'tsū-kak', 'chū-kak'],
    ['自私', '自私', 'tsū-su', 'chū-su'],
    ['自由', '自由', 'tsū-iû', 'chū-iû'],
    ['自愿', '自願', 'tsū-guān', 'chū-goān'],
    ['综合', '綜合', 'tsong-ha̍p', 'chong-ha̍p'],
    ['总裁', '總裁', 'tsóng-tshâi', 'chóng-chhâi'],
    ['总共', '總共', 'tsóng-kiōng', 'chóng-kiōng'],
    ['总理', '總理', 'tsóng-lí', 'chóng-lí'],
    ['总算', '總算', 'tsóng-sǹg', 'chóng-sǹg'],
    ['总统', '總統', 'tsóng-thóng', 'chóng-thóng'],
    ['总之', '總之', 'tsóng-tsi', 'chóng-chi'],
    ['组', '組', 'tsóo', 'chó͘'],
    ['组成', '組成', 'tsóo-sîng', 'chó͘-sêng'],
    ['组合', '組合', 'tsóo-ha̍p', 'chó͘-ha̍p'],
    ['组织', '組織', 'tsóo-tsit', 'chó͘-chit'],
    ['阻止', '阻止', 'tsóo-tsí', 'chó͘-chí'],
    ['最初', '最初', 'tsuè-tshoo', 'chòe-chho͘'],
    ['醉', '醉', 'tsuì', 'chuì'],
    ['尊敬', '尊敬', 'tsun-kìng', 'chun-kèng'],
    ['遵守', '遵守', 'tsun-siú', 'chun-siú'],
    ['作品', '作品', 'tsok-phín', 'chok-phín'],
    ['作为', '作為', 'tsok-uî', 'chok-ûi'],
    ['作文', '作文', 'tsok-bûn', 'chok-bûn'],
]
