/**
 * Hand-authored Taiwanese forms for the HSK 4 vocabulary.
 *
 * Written by hand, as HSK 2 and 3 were, and for a reason that holds even here: the thing this
 * list exists to capture is the *reading*, and the reading is where the dictionary's habit of
 * listing a literary form first does the most quiet damage. 辣 is read `hiam` and not `la̍t`;
 * 火 is `hué`; 低 is `kē`. Those are the same word with a different pronunciation, which is
 * exactly what a learner needs and exactly what a character match will not tell you.
 *
 * Where Taiwanese says a different word altogether, the row says so in a note - 厕所 is 便所,
 * 抽烟 is 食薰, 厨房 is 灶跤, 眼镜 is 目鏡.
 *
 * `tools/taigi-check.ts --level 4` reports how these stand up against the source, and how far
 * the dictionary would have been from them.
 */
import type { HandRow } from './handAuthored.ts'

export const HSK4_ROWS: readonly HandRow[] = [
    ['爱情', '愛情', 'ài-tsîng', 'ài-chêng'],
    ['安排', '安排', 'an-pâi', 'an-pâi'],
    ['安全', '安全', 'an-tsuân', 'an-choân'],
    ['按时', '按時', 'àn-sî', 'àn-sî'],
    ['按照', '按照', 'àn-tsiàu', 'àn-chiàu'],
    ['百分之', '百分之', 'pah-hun-tsi', 'pah-hun-chi'],
    ['棒', '棒', 'pāng', 'pāng'],
    ['包子', '包子', 'pau-á', 'pau-á'],
    ['保护', '保護', 'pó-hōo', 'pó-hō͘'],
    ['保证', '保證', 'pó-tsìng', 'pó-chèng'],
    ['报名', '報名', 'pò-miâ', 'pò-miâ'],
    ['抱', '抱', 'phō', 'phō'],
    ['抱歉', '抱歉', 'phō-khiàm', 'phō-khiàm'],
    ['倍', '倍', 'puē', 'pōe'],
    ['本来', '本來', 'pún-lâi', 'pún-lâi'],
    ['笨', '笨', 'pūn', 'pūn'],
    ['比如', '比如', 'pí-lû', 'pí-lû'],
    ['毕业', '畢業', 'pit-gia̍p', 'pit-gia̍p'],
    ['遍', '遍', 'piàn', 'piàn'],
    ['标准', '標準', 'phiau-tsún', 'phiau-chún'],
    ['表格', '表格', 'pió-kik', 'pió-kek'],
    ['表示', '表示', 'piáu-sī', 'piáu-sī'],
    ['表演', '表演', 'piáu-ián', 'piáu-ián'],
    ['表扬', '表揚', 'piáu-iông', 'piáu-iông'],
    ['饼干', '餅乾', 'piánn-kuann', 'piáⁿ-koaⁿ'],
    ['并且', '並且', 'pìng-tshiánn', 'pèng-chhiáⁿ'],
    ['博士', '博士', 'phok-sū', 'phok-sū'],
    ['不过', '不過', 'put-kò', 'put-kò'],
    ['不得不', '不得不', 'put-tik-put', 'put-tek-put'],
    ['不管', '不管', 'put-kuán', 'put-koán'],
    ['不仅', '不僅', 'put-kín', 'put-kín'],
    ['部分', '部分', 'pōo-hūn', 'pō͘-hūn'],
    ['擦', '擦', 'tshat', 'chhat'],
    ['猜', '猜', 'tshai', 'chhai'],
    ['材料', '材料', 'tsâi-liāu', 'châi-liāu'],
    ['参观', '參觀', 'tsham-kuan', 'chham-koan'],
    ['餐厅', '餐廳', 'tshan-thiann', 'chhan-thiaⁿ'],
    ['厕所', '便所', 'piān-sóo', 'piān-só͘', 'the toilet is 便所'],
    ['差不多', '差不多', 'tsha-put-to', 'chha-put-to'],
    ['尝', '嘗', 'siông', 'siông'],
    ['长城', '長城', 'Tn̂g-siânn', 'Tn̂g-siâⁿ'],
    ['长江', '長江', 'Tn̂g-kang', 'Tn̂g-kang'],
    ['场', '場', 'tiûnn', 'tiûⁿ'],
    ['超过', '超過', 'tshiau-kuè', 'chhiau-kòe'],
    ['乘坐', '乘坐', 'sîng-tsō', 'sêng-chō'],
    ['成功', '成功', 'sîng-kong', 'sêng-kong'],
    ['成为', '成為', 'sîng-uî', 'sêng-ûi'],
    ['诚实', '誠實', 'sîng-si̍t', 'sêng-si̍t'],
    ['吃惊', '著驚', 'tio̍h-kiann', 'tio̍h-kiaⁿ', 'to be startled is 著驚'],
    ['重新', '重新', 'tiông-sin', 'tiông-sin'],
    ['抽烟', '食薰', 'tsia̍h-hun', 'chia̍h-hun', 'to smoke is 食薰, literally to eat smoke'],
    ['出差', '出差', 'tshut-tshai', 'chhut-chhai'],
    ['出发', '出發', 'tshut-huat', 'chhut-hoat'],
    ['出生', '出生', 'tshut-senn', 'chhut-seⁿ'],
    ['出现', '出現', 'tshut-hiān', 'chhut-hiān'],
    ['厨房', '灶跤', 'tsàu-kha', 'chàu-kha', 'the kitchen is 灶跤, the hearth'],
    ['传真', '傳真', 'thuân-tsin', 'thoân-chin'],
    ['窗户', '窗仔', 'thang-á', 'thang-á', 'a window is 窗仔'],
    ['词语', '詞語', 'sû-gí', 'sû-gí', 'absent from the extract'],
    ['从来', '從來', 'tsông-lâi', 'chông-lâi'],
    ['粗心', '粗心', 'tshoo-sim', 'chho͘-sim'],
    ['存', '存', 'tsûn', 'chûn'],
    ['错误', '錯誤', 'tshò-gōo', 'chhò-gō͘'],
    ['答案', '答案', 'tap-àn', 'tap-àn'],
    ['打扮', '打扮', 'tánn-pān', 'táⁿ-pān'],
    ['打扰', '打擾', 'tánn-jiáu', 'táⁿ-jiáu'],
    ['打印', '打印', 'tánn-ìn', 'táⁿ-ìn'],
    ['打招呼', '拍招呼', 'phah-tsio-hou', 'phah-chio-hou', 'to greet is 拍招呼, not 打'],
    ['打折', '打折', 'tánn-tsiat', 'táⁿ-chiat'],
    ['打针', '注射', 'tsù-siā', 'chù-siā', 'an injection is 注射'],
    ['大概', '大概', 'tāi-khài', 'tāi-khài'],
    ['大使馆', '大使館', 'tāi-sài-kuán', 'tāi-sài-koán'],
    ['大约', '大約', 'tāi-iok', 'tāi-iok'],
    ['大夫', '醫生', 'i-sing', 'i-seng', 'a doctor is 醫生'],
    ['戴', '戴', 'tì', 'tì'],
    ['当', '當', 'tong', 'tong'],
    ['当时', '當時', 'tong-sî', 'tong-sî'],
    ['刀', '刀', 'to', 'to'],
    ['导游', '導遊', 'tō-iû', 'tō-iû'],
    ['倒', '倒', 'tò', 'tò'],
    ['到处', '四界', 'sì-kè', 'sì-kè', 'everywhere is 四界'],
    ['到底', '到底', 'tàu-té', 'tàu-té'],
    ['道歉', '道歉', 'tō-khiàm', 'tō-khiàm'],
    ['得', '甲', 'kah', 'kah', 'the degree particle, as in HSK 2'],
    ['得意', '得意', 'tik-ì', 'tek-ì'],
    ['登机牌', '登機牌', 'ting-ki-pâi', 'teng-ki-pâi'],
    ['等', '等', 'tán', 'tán'],
    ['低', '低', 'kē', 'kē', 'low is the colloquial reading kē, not te'],
    ['底', '底', 'té', 'té'],
    ['地点', '地點', 'tē-tiám', 'tē-tiám'],
    ['地球', '地球', 'tē-kiû', 'tē-kiû'],
    ['地址', '地址', 'tē-tsí', 'tē-chí'],
    ['掉', '掉', 'tiāu', 'tiāu'],
    ['调查', '調查', 'tiâu-tsa', 'tiâu-cha'],
    ['丢', '丟', 'tiu', 'tiu'],
    ['动作', '動作', 'tōng-tsok', 'tōng-chok'],
    ['堵车', '塞車', 'that-tshia', 'that-chhia', 'a traffic jam is 塞車'],
    ['肚子', '腹肚', 'pak-tóo', 'pak-tó͘', 'the belly is 腹肚'],
    ['短信', '簡訊', 'kán-sìn', 'kán-sìn', 'Taiwan says 簡訊'],
    ['对话', '對話', 'tuì-uē', 'tùi-ōe'],
    ['对面', '對面', 'tuì-bīn', 'tùi-bīn'],
    ['对于', '對於', 'tuì-î', 'tùi-î'],
    ['儿童', '兒童', 'jî-tông', 'jî-tông'],
    ['而', '而', 'jî', 'jî'],
    ['发生', '發生', 'huat-sing', 'hoat-seng'],
    ['发展', '發展', 'huat-tián', 'hoat-tián'],
    ['法律', '法律', 'huat-lu̍t', 'hoat-lu̍t'],
    ['翻译', '翻譯', 'huan-i̍k', 'hoan-e̍k'],
    ['烦恼', '煩惱', 'huân-ló', 'hoân-ló'],
    ['反对', '反對', 'huán-tuì', 'hoán-tùi'],
    ['方法', '方法', 'hong-huat', 'hong-hoat'],
    ['方面', '方面', 'hong-bīn', 'hong-bīn'],
    ['方向', '方向', 'hong-hiòng', 'hong-hiòng'],
    ['房东', '房東', 'pâng-tong', 'pâng-tong'],
    ['放弃', '放棄', 'hòng-khì', 'hòng-khì'],
    ['放暑假', '放暑假', 'hòng-sú-ká', 'hòng-sú-ká'],
    ['放松', '放鬆', 'hòng-sang', 'hòng-sang'],
    ['份', '份', 'hūn', 'hūn'],
    ['丰富', '豐富', 'hong-hù', 'hong-hù'],
    ['否则', '否則', 'hóo-tsik', 'hó͘-chek'],
    ['符合', '符合', 'hû-ha̍p', 'hû-ha̍p'],
    ['付款', '付款', 'hù-khuán', 'hù-khoán'],
    ['复印', '複印', 'ho̍k-ìn', 'ho̍k-ìn'],
    ['复杂', '複雜', 'ho̍k-tsa̍p', 'ho̍k-cha̍p'],
    ['富', '富', 'hù', 'hù'],
    ['父亲', '父親', 'hū-tshin', 'hū-chhin'],
    ['负责', '負責', 'hū-tsik', 'hū-chek'],
    ['改变', '改變', 'kái-piàn', 'kái-piàn'],
    ['干杯', '乾杯', 'kan-pue', 'kan-poe'],
    ['感动', '感動', 'kám-tōng', 'kám-tōng'],
    ['感觉', '感覺', 'kám-kak', 'kám-kak'],
    ['感情', '感情', 'kám-tsîng', 'kám-chêng'],
    ['感谢', '感謝', 'kám-siā', 'kám-siā'],
    ['敢', '敢', 'kánn', 'káⁿ'],
    ['赶', '趕', 'kuánn', 'kóaⁿ'],
    ['干', '幹', 'kàn', 'kàn'],
    ['刚', '剛', 'kang', 'kang'],
    ['高速公路', '高速公路', 'ko-sok-kong-lōo', 'ko-sok-kong-lō͘'],
    ['胳膊', '手骨', 'tshiú-kut', 'chhiú-kut', 'the arm is 手骨'],
    ['各', '各', 'kok', 'kok'],
    ['公里', '公里', 'kong-lí', 'kong-lí'],
    ['功夫', '功夫', 'kang-hu', 'kang-hu'],
    ['工资', '工資', 'kang-tsu', 'kang-chu'],
    ['共同', '共同', 'kiōng-tông', 'kiōng-tông'],
    ['够', '夠', 'kàu', 'kàu'],
    ['购物', '購物', 'kòo-bu̍t', 'kò͘-bu̍t'],
    ['估计', '估計', 'kóo-kè', 'kó͘-kè'],
    ['鼓励', '鼓勵', 'kóo-lē', 'kó͘-lē'],
    ['故意', '故意', 'kòo-ì', 'kò͘-ì'],
    ['顾客', '顧客', 'kòo-kheh', 'kò͘-kheh'],
    ['挂', '掛', 'kuà', 'kòa'],
    ['关键', '關鍵', 'kuan-kiān', 'koan-kiān'],
    ['观众', '觀眾', 'kuan-tsiòng', 'koan-chiòng'],
    ['管理', '管理', 'kuán-lí', 'koán-lí'],
    ['光', '光', 'kng', 'kng'],
    ['广播', '廣播', 'kóng-pòo', 'kóng-pò͘'],
    ['广告', '廣告', 'kóng-kò', 'kóng-kò'],
    ['逛', '踅', 'se̍h', 'se̍h', 'to stroll is 踅'],
    ['规定', '規定', 'kui-tīng', 'kui-tēng'],
    ['国籍', '國籍', 'kok-tsi̍k', 'kok-che̍k'],
    ['国际', '國際', 'kok-tsè', 'kok-chè'],
    ['果汁', '果汁', 'kó-tsiap', 'kó-chiap'],
    ['过程', '過程', 'kuè-tîng', 'kòe-têng'],
    ['海洋', '海洋', 'hái-iûnn', 'hái-iûⁿ'],
    ['害羞', '見笑', 'kiàn-siàu', 'kiàn-siàu', 'shy is 見笑'],
    ['寒假', '寒假', 'hân-ká', 'hân-ká'],
    ['汗', '汗', 'kuānn', 'kōaⁿ'],
    ['航班', '航班', 'hâng-pan', 'hâng-pan'],
    ['好处', '好處', 'hó-tshù', 'hó-chhù'],
    ['好像', '好像', 'hó-tshiūnn', 'hó-chhiūⁿ'],
    ['号码', '號碼', 'hō-bé', 'hō-bé'],
    ['合格', '合格', 'ha̍p-kik', 'ha̍p-kek'],
    ['合适', '合適', 'ha̍p-sik', 'ha̍p-sek'],
    ['盒子', '盒仔', 'a̍p-á', 'a̍p-á'],
    ['厚', '厚', 'kāu', 'kāu'],
    ['后悔', '後悔', 'hōo-hué', 'hō͘-hóe'],
    ['互联网', '網路', 'bāng-lōo', 'bāng-lō͘', 'the Internet is 網路'],
    ['互相', '互相', 'hōo-siong', 'hō͘-siong'],
    ['护士', '護士', 'hōo-sū', 'hō͘-sū'],
    ['怀疑', '懷疑', 'huâi-gî', 'hoâi-gî'],
    ['回忆', '回憶', 'huê-ik', 'hôe-ek'],
    ['活动', '活動', 'hua̍t-tōng', 'hoa̍t-tōng'],
    ['活泼', '活潑', 'hua̍t-phuat', 'hoa̍t-phoat'],
    ['火', '火', 'hué', 'hóe'],
    ['获得', '獲得', 'hi̍k-tik', 'he̍k-tek'],
    ['基础', '基礎', 'ki-tshóo', 'ki-chhó͘'],
    ['激动', '激動', 'kik-tōng', 'kek-tōng'],
    ['积极', '積極', 'tsik-ki̍k', 'chek-ke̍k'],
    ['积累', '積累', 'tsik-luī', 'chek-luī'],
    ['即使', '即使', 'tsik-sú', 'chek-sú'],
    ['及时', '及時', 'ki̍p-sî', 'ki̍p-sî'],
    ['寄', '寄', 'kià', 'kià'],
    ['技术', '技術', 'ki-su̍t', 'ki-su̍t'],
    ['既然', '既然', 'kì-jiân', 'kì-jiân'],
    ['继续', '繼續', 'kè-sio̍k', 'kè-sio̍k'],
    ['计划', '計劃', 'kè-uē', 'kè-ōe'],
    ['记者', '記者', 'kì-tsiá', 'kì-chiá'],
    ['加班', '加班', 'ka-pan', 'ka-pan'],
    ['加油站', '加油站', 'ka-iû-tsām', 'ka-iû-chām'],
    ['家具', '家具', 'ka-kū', 'ka-kū'],
    ['假', '假', 'ké', 'ké', 'fake is the colloquial reading ké'],
    ['价格', '價格', 'kè-kik', 'kè-kek'],
    ['坚持', '堅持', 'kian-tshî', 'kian-chhî'],
    ['减肥', '減肥', 'kiám-puî', 'kiám-pûi'],
    ['减少', '減少', 'kiám-tsió', 'kiám-chió'],
    ['建议', '建議', 'kiàn-gī', 'kiàn-gī'],
    ['将来', '將來', 'tsiong-lâi', 'chiong-lâi'],
    ['奖金', '獎金', 'tsióng-kim', 'chióng-kim'],
    ['降低', '降低', 'kàng-kē', 'kàng-kē'],
    ['降落', '降落', 'kàng-lo̍h', 'kàng-lo̍h'],
    ['交', '交', 'kau', 'kau'],
    ['交流', '交流', 'kau-liû', 'kau-liû'],
    ['交通', '交通', 'kau-thong', 'kau-thong'],
    ['郊区', '郊區', 'kau-khu', 'kau-khu'],
    ['骄傲', '驕傲', 'kiau-ngōo', 'kiau-ngō͘'],
    ['饺子', '水餃', 'tsuí-kiáu', 'chúi-kiáu', 'a dumpling is 水餃'],
    ['教授', '教授', 'kàu-siū', 'kàu-siū'],
    ['教育', '教育', 'kàu-io̍k', 'kàu-io̍k'],
    ['接受', '接受', 'tsiap-siū', 'chiap-siū'],
    ['接着', '接著', 'tsiap-tio̍h', 'chiap-tio̍h'],
    ['结果', '結果', 'kiat-kó', 'kiat-kó'],
    ['节', '節', 'tsiat', 'chiat'],
    ['节约', '節約', 'tsiat-iok', 'chiat-iok'],
    ['解释', '解釋', 'kái-sik', 'kái-sek'],
    ['尽管', '儘管', 'tsīn-kuán', 'chīn-koán'],
    ['紧张', '緊張', 'kín-tiunn', 'kín-tiuⁿ'],
    ['禁止', '禁止', 'kìm-tsí', 'kìm-chí'],
    ['进行', '進行', 'tsìn-hîng', 'chìn-hêng'],
    ['京剧', '京劇', 'king-kio̍k', 'keng-kio̍k'],
    ['精彩', '精彩', 'tsing-tshái', 'cheng-chhái'],
    ['经济', '經濟', 'king-tsè', 'keng-chè'],
    ['经历', '經歷', 'king-li̍k', 'keng-le̍k'],
    ['经验', '經驗', 'king-giām', 'keng-giām'],
    ['景色', '景色', 'kíng-sik', 'kéng-sek'],
    ['警察', '警察', 'kíng-tshat', 'kéng-chhat'],
    ['竞争', '競爭', 'kīng-tsing', 'kēng-cheng'],
    ['竟然', '竟然', 'kìng-jiân', 'kèng-jiân'],
    ['镜子', '鏡仔', 'kiànn-á', 'kiàⁿ-á'],
    ['究竟', '究竟', 'kiù-kìng', 'kiù-kèng'],
    ['举', '舉', 'kí', 'kí'],
    ['举办', '舉辦', 'kí-pān', 'kí-pān'],
    ['举行', '舉行', 'kí-hîng', 'kí-hêng'],
    ['拒绝', '拒絕', 'kī-tsua̍t', 'kī-choa̍t'],
    ['聚会', '聚會', 'tsū-huē', 'chū-hōe'],
    ['距离', '距離', 'kū-lî', 'kū-lî'],
    ['开玩笑', '講耍笑', 'kóng-sńg-tshiò', 'kóng-sńg-chhiò', 'to joke is 講耍笑'],
    ['开心', '歡喜', 'huann-hí', 'hoaⁿ-hí', 'happy is 歡喜'],
    ['看法', '看法', 'khuànn-huat', 'khòaⁿ-hoat'],
    ['烤鸭', '烤鴨', 'khó-ah', 'khó-ah'],
    ['考虑', '考慮', 'khó-lī', 'khó-lī'],
    ['棵', '棵', 'kho', 'kho'],
    ['科学', '科學', 'kho-ha̍k', 'kho-ha̍k'],
    ['咳嗽', '咳嗽', 'ka-sàu', 'ka-sàu'],
    ['可怜', '可憐', 'khó-lîn', 'khó-lîn'],
    ['可是', '毋過', 'm̄-koh', 'm̄-koh', 'but is usually 毋過'],
    ['可惜', '可惜', 'khó-sik', 'khó-sek'],
    ['客厅', '客廳', 'kheh-thiann', 'kheh-thiaⁿ'],
    ['肯定', '肯定', 'khíng-tīng', 'khéng-tēng'],
    ['空', '空', 'khang', 'khang'],
    ['空气', '空氣', 'khong-khì', 'khong-khì'],
    ['恐怕', '恐怕', 'khióng-phànn', 'khióng-phàⁿ'],
    ['苦', '苦', 'khóo', 'khó͘'],
    ['矿泉水', '礦泉水', 'khòng-tsuân-tsuí', 'khòng-choân-chúi'],
    ['困', '困', 'khùn', 'khùn'],
    ['困难', '困難', 'khùn-lân', 'khùn-lân'],
    ['垃圾桶', '垃圾桶', 'lah-sap-tháng', 'lah-sap-tháng', 'rubbish is 垃圾 lah-sap'],
    ['拉', '拉', 'la', 'la'],
    ['辣', '辣', 'hiam', 'hiam', 'spicy is the colloquial reading hiam'],
    ['来不及', '袂赴', 'bē-hù', 'bē-hù', "too late is 袂赴, 'cannot make it'"],
    ['来得及', '會赴', 'ē-hù', 'ē-hù', 'in time is 會赴'],
    ['来自', '來自', 'lâi-tsū', 'lâi-chū'],
    ['懒', '懶', 'lán', 'lán'],
    ['浪费', '浪費', 'lōng-huì', 'lōng-hùi'],
    ['浪漫', '浪漫', 'lōng-bān', 'lōng-bān'],
    ['老虎', '虎', 'hóo', 'hó͘', 'a tiger is simply 虎'],
    ['冷静', '冷靜', 'líng-tsīng', 'léng-chēng'],
    ['理发', '剃頭', 'thì-thâu', 'thì-thâu', 'a haircut is 剃頭'],
    ['理解', '理解', 'lí-kái', 'lí-kái'],
    ['理想', '理想', 'lí-sióng', 'lí-sióng'],
    ['礼拜天', '禮拜日', 'lé-pài-ji̍t', 'lé-pài-ji̍t', 'Sunday is 禮拜日'],
    ['礼貌', '禮貌', 'lé-māu', 'lé-māu'],
    ['例如', '例如', 'lē-jû', 'lē-jû'],
    ['力气', '力氣', 'la̍t-khì', 'la̍t-khì'],
    ['厉害', '厲害', 'lī-hāi', 'lī-hāi'],
    ['俩', '兩個', 'nn̄g-ê', 'nn̄g-ê', '俩 is simply 兩個'],
    ['联系', '聯絡', 'liân-lo̍k', 'liân-lo̍k', 'to contact is 聯絡'],
    ['连', '連', 'liân', 'liân'],
    ['凉快', '涼快', 'liâng-khuài', 'liâng-khòai'],
    ['零钱', '零錢', 'lîng-tsînn', 'lêng-chîⁿ'],
    ['另外', '另外', 'līng-guā', 'lēng-gōa'],
    ['流利', '流利', 'liû-lī', 'liû-lī'],
    ['流行', '流行', 'liû-hîng', 'liû-hêng'],
    ['留', '留', 'lâu', 'lâu'],
    ['旅行', '旅行', 'lú-hîng', 'lú-hêng'],
    ['乱', '亂', 'luān', 'loān'],
    ['律师', '律師', 'lu̍t-su', 'lu̍t-su'],
    ['麻烦', '麻煩', 'mâ-huân', 'mâ-hoân'],
    ['马虎', '馬虎', 'má-hu', 'má-hu'],
    ['满', '滿', 'muá', 'móa'],
    ['毛', '毛', 'mn̂g', 'mn̂g'],
    ['毛巾', '面巾', 'bīn-kin', 'bīn-kin', 'a towel is 面巾'],
    ['美丽', '美麗', 'bí-lē', 'bí-lē'],
    ['梦', '夢', 'bāng', 'bāng', 'a dream is the colloquial reading bāng'],
    ['迷路', '迷路', 'bê-lōo', 'bê-lō͘'],
    ['密码', '密碼', 'bi̍t-bé', 'bi̍t-bé'],
    ['免费', '免費', 'bián-huì', 'bián-hùi'],
    ['秒', '秒', 'bió', 'bió'],
    ['民族', '民族', 'bîn-tso̍k', 'bîn-cho̍k'],
    ['母亲', '母親', 'bú-tshin', 'bú-chhin'],
    ['目的', '目的', 'bo̍k-tik', 'bo̍k-tek'],
    ['耐心', '耐心', 'nāi-sim', 'nāi-sim'],
    ['难道', '敢講', 'kánn-kóng', 'káⁿ-kóng', "don't tell me is 敢講"],
    ['难受', '艱苦', 'kan-khóo', 'kan-khó͘', 'to feel unwell is 艱苦'],
    ['内', '內', 'lāi', 'lāi'],
    ['内容', '內容', 'lāi-iông', 'lāi-iông'],
    ['能力', '能力', 'lîng-li̍k', 'lêng-le̍k'],
    ['年龄', '年齡', 'nî-lîng', 'nî-lêng'],
    ['弄', '弄', 'lāng', 'lāng'],
    ['暖和', '溫暖', 'un-luán', 'un-loán', 'warm is 溫暖'],
    ['偶尔', '有時', 'ū-sî', 'ū-sî', 'occasionally is 有時'],
    ['排队', '排隊', 'pâi-tuī', 'pâi-tuī'],
    ['排列', '排列', 'pâi-lia̍t', 'pâi-lia̍t'],
    ['判断', '判斷', 'phuàn-tuàn', 'phoàn-toàn'],
    ['陪', '陪', 'puê', 'pôe'],
    ['批评', '批評', 'phue-phîng', 'phoe-phêng'],
    ['皮肤', '皮膚', 'phuê-hu', 'phôe-hu'],
    ['脾气', '脾氣', 'phî-khì', 'phî-khì'],
    ['篇', '篇', 'phinn', 'phiⁿ'],
    ['骗', '騙', 'phiàn', 'phiàn'],
    ['乒乓球', '桌球', 'toh-kiû', 'toh-kiû', 'table tennis is 桌球 in Taiwan'],
    ['平时', '平時', 'pîng-sî', 'pêng-sî'],
    ['破', '破', 'phuà', 'phòa'],
    ['葡萄', '葡萄', 'phû-tô', 'phû-tô'],
    ['普遍', '普遍', 'phóo-phiàn', 'phó͘-phiàn'],
    ['普通话', '國語', 'kok-gí', 'kok-gí', 'Mandarin is 國語 in Taiwan'],
    ['其次', '其次', 'kî-tshù', 'kî-chhù'],
    ['其中', '其中', 'kî-tiong', 'kî-tiong'],
    ['气候', '氣候', 'khì-hāu', 'khì-hāu'],
    ['千万', '千萬', 'tshian-bān', 'chhian-bān'],
    ['签证', '簽證', 'tshiam-tsìng', 'chhiam-chèng'],
    ['敲', '敲', 'khau', 'khau'],
    ['桥', '橋', 'kiô', 'kiô'],
    ['巧克力', '巧克力', 'khiáu-khik-la̍t', 'khiáu-khek-la̍t'],
    ['亲戚', '親戚', 'tshin-tshik', 'chhin-chhek'],
    ['轻', '輕', 'khin', 'khin'],
    ['轻松', '輕鬆', 'khin-sang', 'khin-sang'],
    ['情况', '情況', 'tsîng-hóng', 'chêng-hóng'],
    ['穷', '窮', 'kîng', 'kêng'],
    ['区别', '區別', 'khu-pia̍t', 'khu-pia̍t'],
    ['取', '取', 'tshú', 'chhú'],
    ['全部', '全部', 'tsuân-pōo', 'choân-pō͘'],
    ['缺点', '缺點', 'khuat-tiám', 'khoat-tiám'],
    ['缺少', '缺少', 'khuat-tsió', 'khoat-chió'],
    ['却', '顛倒', 'tian-tò', 'tian-tò', 'but, however is 顛倒'],
    ['确实', '確實', 'khak-si̍t', 'khak-si̍t'],
    ['然而', '然而', 'jiân-jî', 'jiân-jî'],
    ['热闹', '鬧熱', 'lāu-jia̍t', 'lāu-jia̍t', 'bustling is 鬧熱'],
    ['任何', '任何', 'jīm-hô', 'jīm-hô'],
    ['任务', '任務', 'jīm-bū', 'jīm-bū'],
    ['扔', '擲', 'tàn', 'tàn', 'to throw is 擲'],
    ['仍然', '仍然', 'jîng-jiân', 'jêng-jiân'],
    ['日记', '日記', 'ji̍t-kì', 'ji̍t-kì'],
    ['入口', '入口', 'ji̍p-kháu', 'ji̍p-kháu'],
    ['散步', '散步', 'sàn-pōo', 'sàn-pō͘'],
    ['森林', '森林', 'sim-lîm', 'sim-lîm'],
    ['沙发', '膨椅', 'phòng-í', 'phòng-í', 'a sofa is 膨椅'],
    ['伤心', '傷心', 'siong-sim', 'siong-sim'],
    ['商量', '商量', 'siong-liông', 'siong-liông'],
    ['稍微', '稍微', 'siau-bî', 'siau-bî'],
    ['勺子', '匙仔', 'sî-á', 'sî-á', 'a spoon is 匙仔'],
    ['社会', '社會', 'siā-huē', 'siā-hōe'],
    ['深', '深', 'tshim', 'chhim'],
    ['申请', '申請', 'sin-tshíng', 'sin-chhéng'],
    ['甚至', '甚至', 'sīm-tsì', 'sīm-chì'],
    ['生活', '生活', 'sing-hua̍t', 'seng-hoa̍t'],
    ['生命', '生命', 'sìng-bīng', 'sèng-bēng'],
    ['生意', '生意', 'sing-ì', 'seng-ì'],
    ['省', '省', 'síng', 'séng'],
    ['剩', '賰', 'tshun', 'chhun', 'to be left over is 賰'],
    ['失败', '失敗', 'sit-pāi', 'sit-pāi'],
    ['失望', '失望', 'sit-bōng', 'sit-bōng'],
    ['师傅', '師傅', 'sai-hū', 'sai-hū'],
    ['十分', '十分', 'tsa̍p-hun', 'cha̍p-hun'],
    ['实际', '實際', 'si̍t-tsè', 'si̍t-chè'],
    ['实在', '實在', 'si̍t-tsāi', 'si̍t-chāi'],
    ['使', '使', 'sú', 'sú'],
    ['使用', '使用', 'sú-iōng', 'sú-iōng'],
    ['世纪', '世紀', 'sè-kí', 'sè-kí'],
    ['是否', '是否', 'sī-hóo', 'sī-hó͘'],
    ['适合', '適合', 'sik-ha̍p', 'sek-ha̍p'],
    ['适应', '適應', 'sik-ìng', 'sek-èng'],
    ['收', '收', 'siu', 'siu'],
    ['收入', '收入', 'siu-ji̍p', 'siu-ji̍p'],
    ['收拾', '收拾', 'siu-si̍p', 'siu-si̍p'],
    ['首都', '首都', 'siú-too', 'siú-to͘'],
    ['首先', '首先', 'siú-sian', 'siú-sian'],
    ['受不了', '擋袂牢', 'tòng-bē-tiâu', 'tòng-bē-tiâu', 'unbearable is 擋袂牢'],
    ['受到', '受到', 'siū-tio̍h', 'siū-tio̍h'],
    ['售货员', '店員', 'tiàm-uân', 'tiàm-oân', 'a salesperson is 店員'],
    ['输', '輸', 'su', 'su'],
    ['熟悉', '熟悉', 'si̍k-sik', 'se̍k-sek'],
    ['数量', '數量', 'sòo-liōng', 'sò͘-liōng'],
    ['数字', '數字', 'sòo-jī', 'sò͘-jī'],
    ['帅', '緣投', 'iân-tâu', 'iân-tâu', 'handsome is 緣投'],
    ['顺便', '順便', 'sūn-piān', 'sūn-piān'],
    ['顺利', '順利', 'sūn-lī', 'sūn-lī'],
    ['顺序', '順序', 'sūn-sī', 'sūn-sī'],
    ['说明', '說明', 'suat-bîng', 'soat-bêng'],
    ['硕士', '碩士', 'si̍k-sū', 'se̍k-sū'],
    ['死', '死', 'sí', 'sí'],
    ['塑料袋', '塑膠袋', 'sok-ka-tē', 'sok-ka-tē', 'a plastic bag is 塑膠袋'],
    ['速度', '速度', 'sok-tōo', 'sok-tō͘'],
    ['酸', '酸', 'sng', 'sng'],
    ['随便', '隨便', 'suî-piān', 'sûi-piān'],
    ['随着', '隨著', 'suî-tio̍h', 'sûi-tio̍h'],
    ['孙子', '孫仔', 'sun-á', 'sun-á'],
    ['所有', '所有', 'sóo-ū', 'só͘-ū'],
    ['台', '桌', 'toh', 'toh', 'a desk is 桌'],
    ['抬', '抬', 'kia̍h', 'kia̍h'],
    ['态度', '態度', 'thài-tōo', 'thài-tō͘'],
    ['弹钢琴', '彈鋼琴', 'tuân-kòng-khîm', 'toân-kòng-khîm', 'absent from the extract'],
    ['谈', '談', 'tâm', 'tâm'],
    ['汤', '湯', 'thng', 'thng'],
    ['糖', '糖', 'thn̂g', 'thn̂g'],
    ['躺', '躺', 'thóng', 'thóng'],
    ['趟', '趟', 'thàng', 'thàng'],
    ['讨论', '討論', 'thó-lūn', 'thó-lūn'],
    ['讨厌', '討厭', 'thó-ià', 'thó-ià'],
    ['特点', '特點', 'ti̍k-tiám', 'te̍k-tiám'],
    ['提', '提', 'the̍h', 'the̍h'],
    ['提供', '提供', 'thê-kiong', 'thê-kiong'],
    ['提前', '提前', 'thê-tsîng', 'thê-chêng'],
    ['提醒', '提醒', 'thê-tshínn', 'thê-chhíⁿ'],
    ['填空', '填空', 'thinn-khòng', 'thiⁿ-khòng', 'absent from the extract'],
    ['条件', '條件', 'tiâu-kiānn', 'tiâu-kiāⁿ'],
    ['停', '停', 'thîng', 'thêng'],
    ['挺', '挺', 'thíng', 'théng'],
    ['通过', '通過', 'thong-kuè', 'thong-kòe'],
    ['通知', '通知', 'thong-ti', 'thong-ti'],
    ['同情', '同情', 'tông-tsîng', 'tông-chêng'],
    ['同时', '同時', 'tông-sî', 'tông-sî'],
    ['推', '推', 'the', 'the'],
    ['推迟', '推遲', 'the-tî', 'the-tî', 'absent from the extract'],
    ['脱', '脫', 'thuat', 'thoat'],
    ['袜子', '襪仔', 'buē-á', 'bōe-á'],
    ['完全', '完全', 'uân-tsuân', 'oân-choân'],
    ['往往', '往往', 'óng-óng', 'óng-óng'],
    ['网球', '網球', 'bāng-kiû', 'bāng-kiû'],
    ['网站', '網站', 'bāng-tsām', 'bāng-chām'],
    ['危险', '危險', 'guî-hiám', 'gûi-hiám'],
    ['卫生间', '洗手間', 'sé-tshiú-king', 'sé-chhiú-keng', '便所 is taken by 厕所'],
    ['味道', '味道', 'bī-tō', 'bī-tō'],
    ['温度', '溫度', 'un-tōo', 'un-tō͘'],
    ['文章', '文章', 'bûn-tsiong', 'bûn-chiong'],
    ['污染', '汙染', 'u-jiám', 'u-jiám'],
    ['无', '無', 'bô', 'bô'],
    ['无聊', '無聊', 'bô-liâu', 'bô-liâu'],
    ['无论', '無論', 'bô-lūn', 'bô-lūn'],
    ['误会', '誤會', 'gōo-huē', 'gō͘-hōe'],
    ['吸引', '吸引', 'khip-ín', 'khip-ín'],
    ['西红柿', '番茄', 'huan-kiô', 'hoan-kiô', 'a tomato is 番茄'],
    ['咸', '鹹', 'kiâm', 'kiâm', 'salty is the colloquial reading kiâm'],
    ['现金', '現金', 'hiān-kim', 'hiān-kim'],
    ['羡慕', '欣羨', 'him-siān', 'him-siān', 'to envy is 欣羨'],
    ['相反', '相反', 'siong-huán', 'siong-hoán'],
    ['相同', '相同', 'siong-tông', 'siong-tông'],
    ['香', '香', 'phang', 'phang', 'fragrant is the colloquial reading phang'],
    ['详细', '詳細', 'siông-sè', 'siông-sè'],
    ['响', '響', 'hiáng', 'hiáng'],
    ['橡皮', '樹奶擦', 'tshiū-ni-tshat', 'chhiū-ni-chhat', 'an eraser is 樹奶擦'],
    ['消息', '消息', 'siau-sit', 'siau-sit'],
    ['小吃', '小吃', 'sió-tsia̍h', 'sió-chia̍h'],
    ['小伙子', '少年家', 'siàu-liân-ke', 'siàu-liân-ke', 'a lad is 少年家'],
    ['小说', '小說', 'sió-suat', 'sió-soat'],
    ['效果', '效果', 'hāu-kó', 'hāu-kó'],
    ['笑话', '笑話', 'tshiò-uē', 'chhiò-ōe'],
    ['心情', '心情', 'sim-tsîng', 'sim-chêng'],
    ['辛苦', '辛苦', 'sin-khóo', 'sin-khó͘'],
    ['信封', '信封', 'sìn-hong', 'sìn-hong'],
    ['信息', '信息', 'sìn-sit', 'sìn-sit'],
    ['信心', '信心', 'sìn-sim', 'sìn-sim'],
    ['兴奋', '興奮', 'hìng-hùn', 'hèng-hùn'],
    ['行', '行', 'kiânn', 'kiâⁿ'],
    ['醒', '醒', 'tshínn', 'chhíⁿ'],
    ['幸福', '幸福', 'hīng-hok', 'hēng-hok'],
    ['性别', '性別', 'sìng-pia̍t', 'sèng-pia̍t'],
    ['性格', '性格', 'sìng-kik', 'sèng-kek'],
    ['修理', '修理', 'siu-lí', 'siu-lí'],
    ['许多', '許多', 'hú-to', 'hú-to'],
    ['学期', '學期', 'ha̍k-kî', 'ha̍k-kî'],
    ['呀', '呀', '--iah', '--iah'],
    ['压力', '壓力', 'ap-li̍k', 'ap-le̍k'],
    ['牙膏', '牙膏', 'gê-ko', 'gê-ko'],
    ['亚洲', '亞洲', 'A-tsiu', 'A-chiu'],
    ['严格', '嚴格', 'giâm-kik', 'giâm-kek'],
    ['严重', '嚴重', 'giâm-tiōng', 'giâm-tiōng'],
    ['盐', '鹽', 'iâm', 'iâm'],
    ['研究', '研究', 'gián-kiù', 'gián-kiù'],
    ['演出', '演出', 'ián-tshut', 'ián-chhut'],
    ['演员', '演員', 'ián-uân', 'ián-oân'],
    ['眼镜', '目鏡', 'ba̍k-kiànn', 'ba̍k-kiàⁿ', 'spectacles are 目鏡'],
    ['阳光', '陽光', 'iông-kong', 'iông-kong'],
    ['养成', '養成', 'ióng-sîng', 'ióng-sêng'],
    ['样子', '款', 'khuán', 'khóan', 'manner, appearance is 款'],
    ['邀请', '邀請', 'iau-tshiánn', 'iau-chhiáⁿ'],
    ['要是', '若是', 'nā-sī', 'nā-sī'],
    ['钥匙', '鎖匙', 'só-sî', 'só-sî', 'a key is 鎖匙'],
    ['也许', '也許', 'iá-hí', 'iá-hí'],
    ['叶子', '葉仔', 'hio̍h-á', 'hio̍h-á'],
    ['页', '頁', 'ia̍h', 'ia̍h'],
    ['一切', '一切', 'it-tshè', 'it-chhè'],
    ['以', '以', 'í', 'í'],
    ['以为', '以為', 'í-uî', 'í-ûi'],
    ['意见', '意見', 'ì-kiàn', 'ì-kiàn'],
    ['艺术', '藝術', 'gē-su̍t', 'gē-su̍t'],
    ['因此', '因此', 'in-tshú', 'in-chhú'],
    ['引起', '引起', 'ín-khí', 'ín-khí'],
    ['印象', '印象', 'ìn-siōng', 'ìn-siōng'],
    ['赢', '贏', 'iânn', 'iâⁿ'],
    ['应聘', '應聘', 'ìng-phìng', 'èng-phèng'],
    ['勇敢', '勇敢', 'ióng-kám', 'ióng-kám'],
    ['永远', '永遠', 'íng-uán', 'éng-oán'],
    ['优点', '優點', 'iu-tiám', 'iu-tiám'],
    ['优秀', '優秀', 'iu-siù', 'iu-siù'],
    ['幽默', '幽默', 'iu-ba̍k', 'iu-ba̍k'],
    ['尤其', '尤其', 'iû-kî', 'iû-kî'],
    ['由', '由', 'iû', 'iû'],
    ['由于', '由於', 'iû-î', 'iû-î'],
    ['邮局', '郵局', 'iû-kio̍k', 'iû-kio̍k'],
    ['友好', '友好', 'iú-hó', 'iú-hó'],
    ['友谊', '友誼', 'iú-gî', 'iú-gî'],
    ['有趣', '有趣', 'iú-tshù', 'iú-chhù'],
    ['于是', '於是', 'î-sī', 'î-sī'],
    ['愉快', '愉快', 'jû-khuài', 'jû-khòai'],
    ['与', '與', 'ī', 'ī'],
    ['羽毛球', '羽毛球', 'ú-môo-kiû', 'ú-mô͘-kiû', 'absent from the extract'],
    ['语法', '語法', 'gí-huat', 'gí-hoat'],
    ['语言', '語言', 'gí-giân', 'gí-giân'],
    ['预习', '預習', 'ī-si̍p', 'ī-si̍p', 'absent from the extract'],
    ['原来', '原來', 'guân-lâi', 'goân-lâi'],
    ['原谅', '原諒', 'guân-liōng', 'goân-liōng'],
    ['原因', '原因', 'guân-in', 'goân-in'],
    ['约会', '約會', 'iok-huē', 'iok-hōe'],
    ['阅读', '閱讀', 'ia̍t-tho̍k', 'ia̍t-tho̍k'],
    ['云', '雲', 'hûn', 'hûn'],
    ['允许', '允許', 'ún-hí', 'ún-hí'],
    ['杂志', '雜誌', 'tsa̍p-tsì', 'cha̍p-chì'],
    ['咱们', '咱', 'lán', 'lán', 'inclusive we is 咱'],
    ['暂时', '暫時', 'tsiām-sî', 'chiām-sî'],
    ['脏', '垃圾', 'lah-sap', 'lah-sap', 'dirty is 垃圾 lah-sap'],
    ['责任', '責任', 'tsik-jīm', 'chek-jīm'],
    ['增加', '增加', 'tsing-ka', 'cheng-ka'],
    ['占线', '佔線', 'tsiàm-suànn', 'chiàm-sòaⁿ'],
    ['招聘', '招聘', 'tsiau-phìng', 'chiau-phèng', 'absent from the extract'],
    ['照', '照', 'tsiàu', 'chiàu'],
    ['真正', '真正', 'tsin-tsiànn', 'chin-chiàⁿ'],
    ['整理', '整理', 'tsíng-lí', 'chéng-lí'],
    ['正常', '正常', 'tsìng-siông', 'chèng-siông'],
    ['正好', '正好', 'tsìng-hó', 'chèng-hó'],
    ['正确', '正確', 'tsìng-khak', 'chèng-khak'],
    ['正式', '正式', 'tsìng-sik', 'chèng-sek'],
    ['证明', '證明', 'tsìng-bîng', 'chèng-bêng'],
    ['之', '之', 'tsi', 'chi', 'absent from the extract'],
    ['支持', '支持', 'tsi-tshî', 'chi-chhî'],
    ['知识', '知識', 'ti-sik', 'ti-sek', 'absent from the extract'],
    ['值得', '值得', 'ta̍t-tit', 'ta̍t-tit'],
    ['植物', '植物', 'ti̍t-bu̍t', 'ti̍t-bu̍t'],
    ['直接', '直接', 'ti̍t-tsiap', 'ti̍t-chiap'],
    ['职业', '職業', 'tsit-gia̍p', 'chit-gia̍p'],
    ['只好', '只好', 'tsí-hó', 'chí-hó'],
    ['只要', '只要', 'tsí-iàu', 'chí-iàu'],
    ['指', '指', 'tsí', 'chí'],
    ['至少', '至少', 'tsì-tsió', 'chì-chió'],
    ['质量', '質量', 'tsit-liōng', 'chit-liōng'],
    ['重', '重', 'tāng', 'tāng', 'heavy is the colloquial reading tāng'],
    ['重点', '重點', 'tiōng-tiám', 'tiōng-tiám'],
    ['重视', '重視', 'tiōng-sī', 'tiōng-sī'],
    ['周围', '周圍', 'tsiu-uî', 'chiu-ûi'],
    ['主意', '主意', 'tsú-ì', 'chú-ì'],
    ['祝贺', '祝賀', 'tsiok-hō', 'chiok-hō'],
    ['著名', '著名', 'tù-bîng', 'tù-bêng'],
    ['专门', '專門', 'tsuan-bûn', 'choan-bûn'],
    ['专业', '專業', 'tsuan-gia̍p', 'choan-gia̍p'],
    ['转', '轉', 'tńg', 'tńg'],
    ['赚', '賺', 'tsuán', 'chóan'],
    ['准确', '準確', 'tsún-khak', 'chún-khak'],
    ['准时', '準時', 'tsún-sî', 'chún-sî'],
    ['仔细', '仔細', 'tsú-sè', 'chú-sè'],
    ['自然', '自然', 'tsū-jiân', 'chū-jiân'],
    ['自信', '自信', 'tsū-sìn', 'chū-sìn'],
    ['总结', '總結', 'tsóng-kiat', 'chóng-kiat'],
    ['租', '租', 'tsoo', 'cho͘'],
    ['最好', '上好', 'siōng-hó', 'siōng-hó', 'the best is 上好'],
    ['尊重', '尊重', 'tsun-tiōng', 'chun-tiōng'],
    ['左右', '左右', 'tsó-iū', 'chó-iū'],
    ['作家', '作家', 'tsok-ka', 'chok-ka'],
    ['作用', '作用', 'tsok-iōng', 'chok-iōng'],
    ['作者', '作者', 'tsok-tsiá', 'chok-chiá'],
    ['座', '座', 'tsō', 'chō'],
    ['座位', '座位', 'tsō-uī', 'chō-ūi'],
]
